cp /home/sness/pdb/mmCIF/al/1alq.cif.gz mmcif
cp /home/sness/pdb/mmCIF/ax/1axb.cif.gz mmcif
cp /home/sness/pdb/mmCIF/bl/1blc.cif.gz mmcif
cp /home/sness/pdb/mmCIF/bl/1blh.cif.gz mmcif
cp /home/sness/pdb/mmCIF/bl/1blp.cif.gz mmcif
cp /home/sness/pdb/mmCIF/bl/1bls.cif.gz mmcif
cp /home/sness/pdb/mmCIF/bs/1bsg.cif.gz mmcif
cp /home/sness/pdb/mmCIF/bt/1bt5.cif.gz mmcif
cp /home/sness/pdb/mmCIF/bt/1btl.cif.gz mmcif
cp /home/sness/pdb/mmCIF/bu/1bue.cif.gz mmcif
cp /home/sness/pdb/mmCIF/bu/1bul.cif.gz mmcif
cp /home/sness/pdb/mmCIF/bz/1bza.cif.gz mmcif
cp /home/sness/pdb/mmCIF/c3/1c3b.cif.gz mmcif
cp /home/sness/pdb/mmCIF/ce/1cef.cif.gz mmcif
cp /home/sness/pdb/mmCIF/ce/1ceg.cif.gz mmcif
cp /home/sness/pdb/mmCIF/ci/1ci8.cif.gz mmcif
cp /home/sness/pdb/mmCIF/ci/1ci9.cif.gz mmcif
cp /home/sness/pdb/mmCIF/ck/1ck3.cif.gz mmcif
cp /home/sness/pdb/mmCIF/dj/1dja.cif.gz mmcif
cp /home/sness/pdb/mmCIF/dj/1djb.cif.gz mmcif
cp /home/sness/pdb/mmCIF/dj/1djc.cif.gz mmcif
cp /home/sness/pdb/mmCIF/dy/1dy6.cif.gz mmcif
cp /home/sness/pdb/mmCIF/e2/1e25.cif.gz mmcif
cp /home/sness/pdb/mmCIF/e3/1e3u.cif.gz mmcif
cp /home/sness/pdb/mmCIF/e4/1e4d.cif.gz mmcif
cp /home/sness/pdb/mmCIF/ei/1ei5.cif.gz mmcif
cp /home/sness/pdb/mmCIF/er/1erm.cif.gz mmcif
cp /home/sness/pdb/mmCIF/er/1ero.cif.gz mmcif
cp /home/sness/pdb/mmCIF/er/1erq.cif.gz mmcif
cp /home/sness/pdb/mmCIF/es/1es2.cif.gz mmcif
cp /home/sness/pdb/mmCIF/es/1es3.cif.gz mmcif
cp /home/sness/pdb/mmCIF/es/1es4.cif.gz mmcif
cp /home/sness/pdb/mmCIF/es/1es5.cif.gz mmcif
cp /home/sness/pdb/mmCIF/es/1esi.cif.gz mmcif
cp /home/sness/pdb/mmCIF/es/1esu.cif.gz mmcif
cp /home/sness/pdb/mmCIF/ew/1ewz.cif.gz mmcif
cp /home/sness/pdb/mmCIF/fc/1fcm.cif.gz mmcif
cp /home/sness/pdb/mmCIF/fc/1fcn.cif.gz mmcif
cp /home/sness/pdb/mmCIF/fc/1fco.cif.gz mmcif
cp /home/sness/pdb/mmCIF/fo/1fof.cif.gz mmcif
cp /home/sness/pdb/mmCIF/fq/1fqg.cif.gz mmcif
cp /home/sness/pdb/mmCIF/fr/1fr1.cif.gz mmcif
cp /home/sness/pdb/mmCIF/fr/1fr6.cif.gz mmcif
cp /home/sness/pdb/mmCIF/fs/1fsw.cif.gz mmcif
cp /home/sness/pdb/mmCIF/fs/1fsy.cif.gz mmcif
cp /home/sness/pdb/mmCIF/g5/1g5u.cif.gz mmcif
cp /home/sness/pdb/mmCIF/g6/1g68.cif.gz mmcif
cp /home/sness/pdb/mmCIF/g6/1g6a.cif.gz mmcif
cp /home/sness/pdb/mmCIF/ga/1ga0.cif.gz mmcif
cp /home/sness/pdb/mmCIF/ga/1ga9.cif.gz mmcif
cp /home/sness/pdb/mmCIF/gc/1gce.cif.gz mmcif
cp /home/sness/pdb/mmCIF/gh/1ghi.cif.gz mmcif
cp /home/sness/pdb/mmCIF/gh/1ghm.cif.gz mmcif
cp /home/sness/pdb/mmCIF/gh/1ghp.cif.gz mmcif
cp /home/sness/pdb/mmCIF/h5/1h5x.cif.gz mmcif
cp /home/sness/pdb/mmCIF/h8/1h8y.cif.gz mmcif
cp /home/sness/pdb/mmCIF/h8/1h8z.cif.gz mmcif
cp /home/sness/pdb/mmCIF/hd/1hd8.cif.gz mmcif
cp /home/sness/pdb/mmCIF/hl/1hlu.cif.gz mmcif
cp /home/sness/pdb/mmCIF/ht/1htz.cif.gz mmcif
cp /home/sness/pdb/mmCIF/hv/1hvb.cif.gz mmcif
cp /home/sness/pdb/mmCIF/hz/1hzo.cif.gz mmcif
cp /home/sness/pdb/mmCIF/i2/1i2s.cif.gz mmcif
cp /home/sness/pdb/mmCIF/i2/1i2w.cif.gz mmcif
cp /home/sness/pdb/mmCIF/i5/1i5q.cif.gz mmcif
cp /home/sness/pdb/mmCIF/ie/1iel.cif.gz mmcif
cp /home/sness/pdb/mmCIF/ie/1iem.cif.gz mmcif
cp /home/sness/pdb/mmCIF/ik/1ikg.cif.gz mmcif
cp /home/sness/pdb/mmCIF/ik/1iki.cif.gz mmcif
cp /home/sness/pdb/mmCIF/iy/1iyo.cif.gz mmcif
cp /home/sness/pdb/mmCIF/iy/1iyp.cif.gz mmcif
cp /home/sness/pdb/mmCIF/iy/1iyq.cif.gz mmcif
cp /home/sness/pdb/mmCIF/iy/1iys.cif.gz mmcif
cp /home/sness/pdb/mmCIF/j3/1j3w.cif.gz mmcif
cp /home/sness/pdb/mmCIF/j9/1j9m.cif.gz mmcif
cp /home/sness/pdb/mmCIF/jt/1jtd.cif.gz mmcif
cp /home/sness/pdb/mmCIF/jt/1jtg.cif.gz mmcif
cp /home/sness/pdb/mmCIF/jv/1jvj.cif.gz mmcif
cp /home/sness/pdb/mmCIF/jw/1jwp.cif.gz mmcif
cp /home/sness/pdb/mmCIF/jw/1jwv.cif.gz mmcif
cp /home/sness/pdb/mmCIF/jw/1jwz.cif.gz mmcif
cp /home/sness/pdb/mmCIF/k0/1k0k.cif.gz mmcif
cp /home/sness/pdb/mmCIF/k2/1k25.cif.gz mmcif
cp /home/sness/pdb/mmCIF/k3/1k38.cif.gz mmcif
cp /home/sness/pdb/mmCIF/k4/1k4e.cif.gz mmcif
cp /home/sness/pdb/mmCIF/k4/1k4f.cif.gz mmcif
cp /home/sness/pdb/mmCIF/k5/1k54.cif.gz mmcif
cp /home/sness/pdb/mmCIF/k5/1k55.cif.gz mmcif
cp /home/sness/pdb/mmCIF/k5/1k56.cif.gz mmcif
cp /home/sness/pdb/mmCIF/k5/1k57.cif.gz mmcif
cp /home/sness/pdb/mmCIF/k6/1k6r.cif.gz mmcif
cp /home/sness/pdb/mmCIF/k6/1k6s.cif.gz mmcif
cp /home/sness/pdb/mmCIF/kd/1kds.cif.gz mmcif
cp /home/sness/pdb/mmCIF/kd/1kdw.cif.gz mmcif
cp /home/sness/pdb/mmCIF/ke/1ke0.cif.gz mmcif
cp /home/sness/pdb/mmCIF/ke/1ke3.cif.gz mmcif
cp /home/sness/pdb/mmCIF/ke/1ke4.cif.gz mmcif
cp /home/sness/pdb/mmCIF/kg/1kge.cif.gz mmcif
cp /home/sness/pdb/mmCIF/kg/1kgf.cif.gz mmcif
cp /home/sness/pdb/mmCIF/kg/1kgg.cif.gz mmcif
cp /home/sness/pdb/mmCIF/kv/1kvl.cif.gz mmcif
cp /home/sness/pdb/mmCIF/kv/1kvm.cif.gz mmcif
cp /home/sness/pdb/mmCIF/l0/1l0d.cif.gz mmcif
cp /home/sness/pdb/mmCIF/l0/1l0e.cif.gz mmcif
cp /home/sness/pdb/mmCIF/l0/1l0f.cif.gz mmcif
cp /home/sness/pdb/mmCIF/l0/1l0g.cif.gz mmcif
cp /home/sness/pdb/mmCIF/l2/1l2s.cif.gz mmcif
cp /home/sness/pdb/mmCIF/lh/1lhy.cif.gz mmcif
cp /home/sness/pdb/mmCIF/li/1li0.cif.gz mmcif
cp /home/sness/pdb/mmCIF/li/1li9.cif.gz mmcif
cp /home/sness/pdb/mmCIF/ll/1ll5.cif.gz mmcif
cp /home/sness/pdb/mmCIF/ll/1ll9.cif.gz mmcif
cp /home/sness/pdb/mmCIF/ll/1llb.cif.gz mmcif
cp /home/sness/pdb/mmCIF/m4/1m40.cif.gz mmcif
cp /home/sness/pdb/mmCIF/m6/1m6k.cif.gz mmcif
cp /home/sness/pdb/mmCIF/mb/1mbl.cif.gz mmcif
cp /home/sness/pdb/mmCIF/mk/1mki.cif.gz mmcif
cp /home/sness/pdb/mmCIF/mp/1mpl.cif.gz mmcif
cp /home/sness/pdb/mmCIF/mw/1mwr.cif.gz mmcif
cp /home/sness/pdb/mmCIF/mw/1mws.cif.gz mmcif
cp /home/sness/pdb/mmCIF/mw/1mwt.cif.gz mmcif
cp /home/sness/pdb/mmCIF/mw/1mwu.cif.gz mmcif
cp /home/sness/pdb/mmCIF/mx/1mxo.cif.gz mmcif
cp /home/sness/pdb/mmCIF/my/1my8.cif.gz mmcif
cp /home/sness/pdb/mmCIF/n4/1n4o.cif.gz mmcif
cp /home/sness/pdb/mmCIF/n9/1n9b.cif.gz mmcif
cp /home/sness/pdb/mmCIF/nj/1nj4.cif.gz mmcif
cp /home/sness/pdb/mmCIF/nr/1nrf.cif.gz mmcif
cp /home/sness/pdb/mmCIF/nx/1nxy.cif.gz mmcif
cp /home/sness/pdb/mmCIF/ny/1ny0.cif.gz mmcif
cp /home/sness/pdb/mmCIF/ny/1nym.cif.gz mmcif
cp /home/sness/pdb/mmCIF/ny/1nyy.cif.gz mmcif
cp /home/sness/pdb/mmCIF/nz/1nzo.cif.gz mmcif
cp /home/sness/pdb/mmCIF/nz/1nzu.cif.gz mmcif
cp /home/sness/pdb/mmCIF/o0/1o07.cif.gz mmcif
cp /home/sness/pdb/mmCIF/o7/1o7e.cif.gz mmcif
cp /home/sness/pdb/mmCIF/om/1ome.cif.gz mmcif
cp /home/sness/pdb/mmCIF/on/1ong.cif.gz mmcif
cp /home/sness/pdb/mmCIF/on/1onh.cif.gz mmcif
cp /home/sness/pdb/mmCIF/pi/1pi4.cif.gz mmcif
cp /home/sness/pdb/mmCIF/pi/1pi5.cif.gz mmcif
cp /home/sness/pdb/mmCIF/pi/1pio.cif.gz mmcif
cp /home/sness/pdb/mmCIF/pw/1pw1.cif.gz mmcif
cp /home/sness/pdb/mmCIF/pw/1pw8.cif.gz mmcif
cp /home/sness/pdb/mmCIF/pw/1pwc.cif.gz mmcif
cp /home/sness/pdb/mmCIF/pw/1pwd.cif.gz mmcif
cp /home/sness/pdb/mmCIF/pw/1pwg.cif.gz mmcif
cp /home/sness/pdb/mmCIF/py/1pyy.cif.gz mmcif
cp /home/sness/pdb/mmCIF/pz/1pzo.cif.gz mmcif
cp /home/sness/pdb/mmCIF/pz/1pzp.cif.gz mmcif
cp /home/sness/pdb/mmCIF/q2/1q2p.cif.gz mmcif
cp /home/sness/pdb/mmCIF/q2/1q2q.cif.gz mmcif
cp /home/sness/pdb/mmCIF/qm/1qme.cif.gz mmcif
cp /home/sness/pdb/mmCIF/qm/1qmf.cif.gz mmcif
cp /home/sness/pdb/mmCIF/rc/1rcj.cif.gz mmcif
cp /home/sness/pdb/mmCIF/rg/1rgy.cif.gz mmcif
cp /home/sness/pdb/mmCIF/rg/1rgz.cif.gz mmcif
cp /home/sness/pdb/mmCIF/rp/1rp5.cif.gz mmcif
cp /home/sness/pdb/mmCIF/s0/1s0w.cif.gz mmcif
cp /home/sness/pdb/mmCIF/s6/1s6r.cif.gz mmcif
cp /home/sness/pdb/mmCIF/sc/1scw.cif.gz mmcif
cp /home/sness/pdb/mmCIF/sd/1sde.cif.gz mmcif
cp /home/sness/pdb/mmCIF/sd/1sdn.cif.gz mmcif
cp /home/sness/pdb/mmCIF/sh/1shv.cif.gz mmcif
cp /home/sness/pdb/mmCIF/sk/1skf.cif.gz mmcif
cp /home/sness/pdb/mmCIF/sk/1sko.cif.gz mmcif
cp /home/sness/pdb/mmCIF/st/1stz.cif.gz mmcif
cp /home/sness/pdb/mmCIF/td/1tdg.cif.gz mmcif
cp /home/sness/pdb/mmCIF/td/1tdl.cif.gz mmcif
cp /home/sness/pdb/mmCIF/te/1tem.cif.gz mmcif
cp /home/sness/pdb/mmCIF/tv/1tvf.cif.gz mmcif
cp /home/sness/pdb/mmCIF/u6/1u60.cif.gz mmcif
cp /home/sness/pdb/mmCIF/uy/1uyn.cif.gz mmcif
cp /home/sness/pdb/mmCIF/ve/1vet.cif.gz mmcif
cp /home/sness/pdb/mmCIF/vm/1vm1.cif.gz mmcif
cp /home/sness/pdb/mmCIF/vq/1vqq.cif.gz mmcif
cp /home/sness/pdb/mmCIF/w5/1w5d.cif.gz mmcif
cp /home/sness/pdb/mmCIF/w7/1w79.cif.gz mmcif
cp /home/sness/pdb/mmCIF/w7/1w7f.cif.gz mmcif
cp /home/sness/pdb/mmCIF/w8/1w8q.cif.gz mmcif
cp /home/sness/pdb/mmCIF/w8/1w8y.cif.gz mmcif
cp /home/sness/pdb/mmCIF/we/1we4.cif.gz mmcif
cp /home/sness/pdb/mmCIF/wy/1wyb.cif.gz mmcif
cp /home/sness/pdb/mmCIF/wy/1wyc.cif.gz mmcif
cp /home/sness/pdb/mmCIF/xa/1xa1.cif.gz mmcif
cp /home/sness/pdb/mmCIF/xa/1xa7.cif.gz mmcif
cp /home/sness/pdb/mmCIF/xg/1xgi.cif.gz mmcif
cp /home/sness/pdb/mmCIF/xg/1xgj.cif.gz mmcif
cp /home/sness/pdb/mmCIF/xk/1xkz.cif.gz mmcif
cp /home/sness/pdb/mmCIF/xp/1xp4.cif.gz mmcif
cp /home/sness/pdb/mmCIF/xp/1xpb.cif.gz mmcif
cp /home/sness/pdb/mmCIF/xx/1xx2.cif.gz mmcif
cp /home/sness/pdb/mmCIF/xx/1xxm.cif.gz mmcif
cp /home/sness/pdb/mmCIF/y5/1y54.cif.gz mmcif
cp /home/sness/pdb/mmCIF/yk/1ykd.cif.gz mmcif
cp /home/sness/pdb/mmCIF/yl/1ylj.cif.gz mmcif
cp /home/sness/pdb/mmCIF/yl/1ylp.cif.gz mmcif
cp /home/sness/pdb/mmCIF/yl/1ylt.cif.gz mmcif
cp /home/sness/pdb/mmCIF/yl/1ylw.cif.gz mmcif
cp /home/sness/pdb/mmCIF/yl/1yly.cif.gz mmcif
cp /home/sness/pdb/mmCIF/yl/1ylz.cif.gz mmcif
cp /home/sness/pdb/mmCIF/ym/1ym1.cif.gz mmcif
cp /home/sness/pdb/mmCIF/ym/1yms.cif.gz mmcif
cp /home/sness/pdb/mmCIF/ym/1ymx.cif.gz mmcif
cp /home/sness/pdb/mmCIF/yq/1yqs.cif.gz mmcif
cp /home/sness/pdb/mmCIF/yt/1yt4.cif.gz mmcif
cp /home/sness/pdb/mmCIF/z6/1z6f.cif.gz mmcif
cp /home/sness/pdb/mmCIF/zc/1zc2.cif.gz mmcif
cp /home/sness/pdb/mmCIF/zg/1zg4.cif.gz mmcif
cp /home/sness/pdb/mmCIF/zg/1zg6.cif.gz mmcif
cp /home/sness/pdb/mmCIF/zk/1zkj.cif.gz mmcif
cp /home/sness/pdb/mmCIF/a3/2a3u.cif.gz mmcif
cp /home/sness/pdb/mmCIF/a4/2a49.cif.gz mmcif
cp /home/sness/pdb/mmCIF/b5/2b5r.cif.gz mmcif
cp /home/sness/pdb/mmCIF/bg/2bg1.cif.gz mmcif
cp /home/sness/pdb/mmCIF/bl/2bls.cif.gz mmcif
cp /home/sness/pdb/mmCIF/c5/2c5w.cif.gz mmcif
cp /home/sness/pdb/mmCIF/c6/2c6w.cif.gz mmcif
cp /home/sness/pdb/mmCIF/dc/2dcf.cif.gz mmcif
cp /home/sness/pdb/mmCIF/dn/2dns.cif.gz mmcif
cp /home/sness/pdb/mmCIF/dr/2drw.cif.gz mmcif
cp /home/sness/pdb/mmCIF/e8/2e8i.cif.gz mmcif
cp /home/sness/pdb/mmCIF/ef/2efu.cif.gz mmcif
cp /home/sness/pdb/mmCIF/ef/2efx.cif.gz mmcif
cp /home/sness/pdb/mmCIF/ex/2ex2.cif.gz mmcif
cp /home/sness/pdb/mmCIF/ex/2ex6.cif.gz mmcif
cp /home/sness/pdb/mmCIF/ex/2ex8.cif.gz mmcif
cp /home/sness/pdb/mmCIF/ex/2ex9.cif.gz mmcif
cp /home/sness/pdb/mmCIF/ex/2exa.cif.gz mmcif
cp /home/sness/pdb/mmCIF/ex/2exb.cif.gz mmcif
cp /home/sness/pdb/mmCIF/ff/2fff.cif.gz mmcif
cp /home/sness/pdb/mmCIF/ff/2ffy.cif.gz mmcif
cp /home/sness/pdb/mmCIF/g2/2g2u.cif.gz mmcif
cp /home/sness/pdb/mmCIF/g2/2g2w.cif.gz mmcif
cp /home/sness/pdb/mmCIF/gd/2gdn.cif.gz mmcif
cp /home/sness/pdb/mmCIF/h0/2h0t.cif.gz mmcif
cp /home/sness/pdb/mmCIF/h0/2h0y.cif.gz mmcif
cp /home/sness/pdb/mmCIF/h1/2h10.cif.gz mmcif
cp /home/sness/pdb/mmCIF/h5/2h5s.cif.gz mmcif
cp /home/sness/pdb/mmCIF/hd/2hdq.cif.gz mmcif
cp /home/sness/pdb/mmCIF/hd/2hdr.cif.gz mmcif
cp /home/sness/pdb/mmCIF/hd/2hds.cif.gz mmcif
cp /home/sness/pdb/mmCIF/hd/2hdu.cif.gz mmcif
cp /home/sness/pdb/mmCIF/hf/2hf6.cif.gz mmcif
cp /home/sness/pdb/mmCIF/hp/2hp5.cif.gz mmcif
cp /home/sness/pdb/mmCIF/hp/2hp6.cif.gz mmcif
cp /home/sness/pdb/mmCIF/hp/2hp9.cif.gz mmcif
cp /home/sness/pdb/mmCIF/hp/2hpb.cif.gz mmcif
cp /home/sness/pdb/mmCIF/i7/2i72.cif.gz mmcif
cp /home/sness/pdb/mmCIF/iw/2iwb.cif.gz mmcif
cp /home/sness/pdb/mmCIF/iw/2iwc.cif.gz mmcif
cp /home/sness/pdb/mmCIF/iw/2iwd.cif.gz mmcif
cp /home/sness/pdb/mmCIF/j7/2j7v.cif.gz mmcif
cp /home/sness/pdb/mmCIF/j8/2j8y.cif.gz mmcif
cp /home/sness/pdb/mmCIF/j9/2j9o.cif.gz mmcif
cp /home/sness/pdb/mmCIF/j9/2j9p.cif.gz mmcif
cp /home/sness/pdb/mmCIF/jb/2jbf.cif.gz mmcif
cp /home/sness/pdb/mmCIF/jc/2jc7.cif.gz mmcif
cp /home/sness/pdb/mmCIF/jc/2jch.cif.gz mmcif
cp /home/sness/pdb/mmCIF/je/2je5.cif.gz mmcif
cp /home/sness/pdb/mmCIF/jk/2jkf.cif.gz mmcif
cp /home/sness/pdb/mmCIF/jk/2jkg.cif.gz mmcif
cp /home/sness/pdb/mmCIF/ol/2olu.cif.gz mmcif
cp /home/sness/pdb/mmCIF/ol/2olv.cif.gz mmcif
cp /home/sness/pdb/mmCIF/os/2osu.cif.gz mmcif
cp /home/sness/pdb/mmCIF/ov/2ov5.cif.gz mmcif
cp /home/sness/pdb/mmCIF/p7/2p74.cif.gz mmcif
cp /home/sness/pdb/mmCIF/p9/2p9v.cif.gz mmcif
cp /home/sness/pdb/mmCIF/pb/2pby.cif.gz mmcif
cp /home/sness/pdb/mmCIF/pu/2pu2.cif.gz mmcif
cp /home/sness/pdb/mmCIF/pu/2pu4.cif.gz mmcif
cp /home/sness/pdb/mmCIF/q9/2q9m.cif.gz mmcif
cp /home/sness/pdb/mmCIF/q9/2q9n.cif.gz mmcif
cp /home/sness/pdb/mmCIF/qm/2qmi.cif.gz mmcif
cp /home/sness/pdb/mmCIF/qp/2qpn.cif.gz mmcif
cp /home/sness/pdb/mmCIF/qy/2qyb.cif.gz mmcif
cp /home/sness/pdb/mmCIF/qz/2qz6.cif.gz mmcif
cp /home/sness/pdb/mmCIF/r9/2r9w.cif.gz mmcif
cp /home/sness/pdb/mmCIF/r9/2r9x.cif.gz mmcif
cp /home/sness/pdb/mmCIF/rc/2rcx.cif.gz mmcif
cp /home/sness/pdb/mmCIF/rl/2rl3.cif.gz mmcif
cp /home/sness/pdb/mmCIF/uw/2uwx.cif.gz mmcif
cp /home/sness/pdb/mmCIF/v1/2v1z.cif.gz mmcif
cp /home/sness/pdb/mmCIF/v2/2v20.cif.gz mmcif
cp /home/sness/pdb/mmCIF/v2/2v2f.cif.gz mmcif
cp /home/sness/pdb/mmCIF/vg/2vgj.cif.gz mmcif
cp /home/sness/pdb/mmCIF/vg/2vgk.cif.gz mmcif
cp /home/sness/pdb/mmCIF/vj/2vjw.cif.gz mmcif
cp /home/sness/pdb/mmCIF/vz/2vzw.cif.gz mmcif
cp /home/sness/pdb/mmCIF/w1/2w1t.cif.gz mmcif
cp /home/sness/pdb/mmCIF/wa/2wad.cif.gz mmcif
cp /home/sness/pdb/mmCIF/wa/2wae.cif.gz mmcif
cp /home/sness/pdb/mmCIF/wa/2waf.cif.gz mmcif
cp /home/sness/pdb/mmCIF/wg/2wgi.cif.gz mmcif
cp /home/sness/pdb/mmCIF/wg/2wgv.cif.gz mmcif
cp /home/sness/pdb/mmCIF/wg/2wgw.cif.gz mmcif
cp /home/sness/pdb/mmCIF/wk/2wk0.cif.gz mmcif
cp /home/sness/pdb/mmCIF/wk/2wke.cif.gz mmcif
cp /home/sness/pdb/mmCIF/wk/2wkh.cif.gz mmcif
cp /home/sness/pdb/mmCIF/wk/2wki.cif.gz mmcif
cp /home/sness/pdb/mmCIF/wu/2wuq.cif.gz mmcif
cp /home/sness/pdb/mmCIF/wy/2wyx.cif.gz mmcif
cp /home/sness/pdb/mmCIF/wz/2wzx.cif.gz mmcif
cp /home/sness/pdb/mmCIF/wz/2wzz.cif.gz mmcif
cp /home/sness/pdb/mmCIF/x0/2x01.cif.gz mmcif
cp /home/sness/pdb/mmCIF/x0/2x02.cif.gz mmcif
cp /home/sness/pdb/mmCIF/x7/2x71.cif.gz mmcif
cp /home/sness/pdb/mmCIF/xd/2xd1.cif.gz mmcif
cp /home/sness/pdb/mmCIF/xd/2xd5.cif.gz mmcif
cp /home/sness/pdb/mmCIF/xd/2xdm.cif.gz mmcif
cp /home/sness/pdb/mmCIF/xe/2xep.cif.gz mmcif
cp /home/sness/pdb/mmCIF/xf/2xf3.cif.gz mmcif
cp /home/sness/pdb/mmCIF/xf/2xfs.cif.gz mmcif
cp /home/sness/pdb/mmCIF/xf/2xft.cif.gz mmcif
cp /home/sness/pdb/mmCIF/xg/2xgn.cif.gz mmcif
cp /home/sness/pdb/mmCIF/xh/2xh9.cif.gz mmcif
cp /home/sness/pdb/mmCIF/xk/2xk1.cif.gz mmcif
cp /home/sness/pdb/mmCIF/xl/2xln.cif.gz mmcif
cp /home/sness/pdb/mmCIF/xq/2xqz.cif.gz mmcif
cp /home/sness/pdb/mmCIF/xr/2xr0.cif.gz mmcif
cp /home/sness/pdb/mmCIF/y2/2y2g.cif.gz mmcif
cp /home/sness/pdb/mmCIF/y2/2y2h.cif.gz mmcif
cp /home/sness/pdb/mmCIF/y2/2y2i.cif.gz mmcif
cp /home/sness/pdb/mmCIF/y2/2y2j.cif.gz mmcif
cp /home/sness/pdb/mmCIF/y2/2y2k.cif.gz mmcif
cp /home/sness/pdb/mmCIF/y2/2y2l.cif.gz mmcif
cp /home/sness/pdb/mmCIF/y2/2y2m.cif.gz mmcif
cp /home/sness/pdb/mmCIF/y2/2y2n.cif.gz mmcif
cp /home/sness/pdb/mmCIF/y2/2y2o.cif.gz mmcif
cp /home/sness/pdb/mmCIF/y2/2y2p.cif.gz mmcif
cp /home/sness/pdb/mmCIF/y2/2y2q.cif.gz mmcif
cp /home/sness/pdb/mmCIF/y5/2y59.cif.gz mmcif
cp /home/sness/pdb/mmCIF/y9/2y91.cif.gz mmcif
cp /home/sness/pdb/mmCIF/z2/2z2l.cif.gz mmcif
cp /home/sness/pdb/mmCIF/z2/2z2m.cif.gz mmcif
cp /home/sness/pdb/mmCIF/zc/2zc3.cif.gz mmcif
cp /home/sness/pdb/mmCIF/zc/2zc4.cif.gz mmcif
cp /home/sness/pdb/mmCIF/zc/2zc5.cif.gz mmcif
cp /home/sness/pdb/mmCIF/zc/2zc6.cif.gz mmcif
cp /home/sness/pdb/mmCIF/zc/2zc7.cif.gz mmcif
cp /home/sness/pdb/mmCIF/zd/2zd8.cif.gz mmcif
cp /home/sness/pdb/mmCIF/zj/2zj9.cif.gz mmcif
cp /home/sness/pdb/mmCIF/zl/2zl1.cif.gz mmcif
cp /home/sness/pdb/mmCIF/zl/2zly.cif.gz mmcif
cp /home/sness/pdb/mmCIF/zm/2zm0.cif.gz mmcif
cp /home/sness/pdb/mmCIF/zm/2zm2.cif.gz mmcif
cp /home/sness/pdb/mmCIF/zm/2zm7.cif.gz mmcif
cp /home/sness/pdb/mmCIF/zm/2zm8.cif.gz mmcif
cp /home/sness/pdb/mmCIF/zm/2zm9.cif.gz mmcif
cp /home/sness/pdb/mmCIF/zm/2zma.cif.gz mmcif
cp /home/sness/pdb/mmCIF/zq/2zq7.cif.gz mmcif
cp /home/sness/pdb/mmCIF/zq/2zq8.cif.gz mmcif
cp /home/sness/pdb/mmCIF/zq/2zq9.cif.gz mmcif
cp /home/sness/pdb/mmCIF/zq/2zqa.cif.gz mmcif
cp /home/sness/pdb/mmCIF/zq/2zqc.cif.gz mmcif
cp /home/sness/pdb/mmCIF/zq/2zqd.cif.gz mmcif
cp /home/sness/pdb/mmCIF/a3/3a3d.cif.gz mmcif
cp /home/sness/pdb/mmCIF/a3/3a3e.cif.gz mmcif
cp /home/sness/pdb/mmCIF/a3/3a3f.cif.gz mmcif
cp /home/sness/pdb/mmCIF/a3/3a3i.cif.gz mmcif
cp /home/sness/pdb/mmCIF/a3/3a3j.cif.gz mmcif
cp /home/sness/pdb/mmCIF/a6/3a65.cif.gz mmcif
cp /home/sness/pdb/mmCIF/a6/3a66.cif.gz mmcif
cp /home/sness/pdb/mmCIF/ag/3agd.cif.gz mmcif
cp /home/sness/pdb/mmCIF/ag/3age.cif.gz mmcif
cp /home/sness/pdb/mmCIF/ag/3agf.cif.gz mmcif
cp /home/sness/pdb/mmCIF/b3/3b3x.cif.gz mmcif
cp /home/sness/pdb/mmCIF/be/3beb.cif.gz mmcif
cp /home/sness/pdb/mmCIF/be/3bec.cif.gz mmcif
cp /home/sness/pdb/mmCIF/bf/3bfc.cif.gz mmcif
cp /home/sness/pdb/mmCIF/bf/3bfd.cif.gz mmcif
cp /home/sness/pdb/mmCIF/bf/3bfe.cif.gz mmcif
cp /home/sness/pdb/mmCIF/bf/3bff.cif.gz mmcif
cp /home/sness/pdb/mmCIF/bf/3bfg.cif.gz mmcif
cp /home/sness/pdb/mmCIF/bl/3blm.cif.gz mmcif
cp /home/sness/pdb/mmCIF/bl/3bls.cif.gz mmcif
cp /home/sness/pdb/mmCIF/bm/3bm6.cif.gz mmcif
cp /home/sness/pdb/mmCIF/br/3brm.cif.gz mmcif
cp /home/sness/pdb/mmCIF/by/3byd.cif.gz mmcif
cp /home/sness/pdb/mmCIF/c4/3c4o.cif.gz mmcif
cp /home/sness/pdb/mmCIF/c4/3c4p.cif.gz mmcif
cp /home/sness/pdb/mmCIF/c5/3c5a.cif.gz mmcif
cp /home/sness/pdb/mmCIF/c7/3c7u.cif.gz mmcif
cp /home/sness/pdb/mmCIF/c7/3c7v.cif.gz mmcif
cp /home/sness/pdb/mmCIF/cg/3cg5.cif.gz mmcif
cp /home/sness/pdb/mmCIF/ci/3cit.cif.gz mmcif
cp /home/sness/pdb/mmCIF/cj/3cjm.cif.gz mmcif
cp /home/sness/pdb/mmCIF/cm/3cmz.cif.gz mmcif
cp /home/sness/pdb/mmCIF/cz/3czd.cif.gz mmcif
cp /home/sness/pdb/mmCIF/d4/3d4f.cif.gz mmcif
cp /home/sness/pdb/mmCIF/dt/3dtm.cif.gz mmcif
cp /home/sness/pdb/mmCIF/dw/3dw0.cif.gz mmcif
cp /home/sness/pdb/mmCIF/dw/3dwk.cif.gz mmcif
cp /home/sness/pdb/mmCIF/dw/3dwz.cif.gz mmcif
cp /home/sness/pdb/mmCIF/e2/3e2k.cif.gz mmcif
cp /home/sness/pdb/mmCIF/e2/3e2l.cif.gz mmcif
cp /home/sness/pdb/mmCIF/ee/3eea.cif.gz mmcif
cp /home/sness/pdb/mmCIF/eq/3equ.cif.gz mmcif
cp /home/sness/pdb/mmCIF/eq/3eqv.cif.gz mmcif
cp /home/sness/pdb/mmCIF/fk/3fkv.cif.gz mmcif
cp /home/sness/pdb/mmCIF/fk/3fkw.cif.gz mmcif
cp /home/sness/pdb/mmCIF/fv/3fv7.cif.gz mmcif
cp /home/sness/pdb/mmCIF/fw/3fwl.cif.gz mmcif
cp /home/sness/pdb/mmCIF/fy/3fyz.cif.gz mmcif
cp /home/sness/pdb/mmCIF/fz/3fzc.cif.gz mmcif
cp /home/sness/pdb/mmCIF/g2/3g2y.cif.gz mmcif
cp /home/sness/pdb/mmCIF/g2/3g2z.cif.gz mmcif
cp /home/sness/pdb/mmCIF/g3/3g30.cif.gz mmcif
cp /home/sness/pdb/mmCIF/g3/3g31.cif.gz mmcif
cp /home/sness/pdb/mmCIF/g3/3g32.cif.gz mmcif
cp /home/sness/pdb/mmCIF/g3/3g34.cif.gz mmcif
cp /home/sness/pdb/mmCIF/g3/3g35.cif.gz mmcif
cp /home/sness/pdb/mmCIF/g4/3g4p.cif.gz mmcif
cp /home/sness/pdb/mmCIF/gm/3gmw.cif.gz mmcif
cp /home/sness/pdb/mmCIF/gq/3gqz.cif.gz mmcif
cp /home/sness/pdb/mmCIF/gr/3gr2.cif.gz mmcif
cp /home/sness/pdb/mmCIF/gr/3grj.cif.gz mmcif
cp /home/sness/pdb/mmCIF/gs/3gsg.cif.gz mmcif
cp /home/sness/pdb/mmCIF/gt/3gtc.cif.gz mmcif
cp /home/sness/pdb/mmCIF/gv/3gv9.cif.gz mmcif
cp /home/sness/pdb/mmCIF/gv/3gvb.cif.gz mmcif
cp /home/sness/pdb/mmCIF/hb/3hbr.cif.gz mmcif
cp /home/sness/pdb/mmCIF/hl/3hl9.cif.gz mmcif
cp /home/sness/pdb/mmCIF/hl/3hlb.cif.gz mmcif
cp /home/sness/pdb/mmCIF/hl/3hlc.cif.gz mmcif
cp /home/sness/pdb/mmCIF/hl/3hld.cif.gz mmcif
cp /home/sness/pdb/mmCIF/hl/3hle.cif.gz mmcif
cp /home/sness/pdb/mmCIF/hl/3hlf.cif.gz mmcif
cp /home/sness/pdb/mmCIF/hl/3hlg.cif.gz mmcif
cp /home/sness/pdb/mmCIF/hl/3hlw.cif.gz mmcif
cp /home/sness/pdb/mmCIF/hr/3hre.cif.gz mmcif
cp /home/sness/pdb/mmCIF/hu/3hum.cif.gz mmcif
cp /home/sness/pdb/mmCIF/hu/3hun.cif.gz mmcif
cp /home/sness/pdb/mmCIF/hu/3huo.cif.gz mmcif
cp /home/sness/pdb/mmCIF/hv/3hvf.cif.gz mmcif
cp /home/sness/pdb/mmCIF/i7/3i7j.cif.gz mmcif
cp /home/sness/pdb/mmCIF/if/3if5.cif.gz mmcif
cp /home/sness/pdb/mmCIF/if/3if6.cif.gz mmcif
cp /home/sness/pdb/mmCIF/ih/3ih8.cif.gz mmcif
cp /home/sness/pdb/mmCIF/ih/3ih9.cif.gz mmcif
cp /home/sness/pdb/mmCIF/ih/3iha.cif.gz mmcif
cp /home/sness/pdb/mmCIF/ih/3ihb.cif.gz mmcif
cp /home/sness/pdb/mmCIF/iq/3iqa.cif.gz mmcif
cp /home/sness/pdb/mmCIF/is/3isg.cif.gz mmcif
cp /home/sness/pdb/mmCIF/it/3it9.cif.gz mmcif
cp /home/sness/pdb/mmCIF/it/3ita.cif.gz mmcif
cp /home/sness/pdb/mmCIF/it/3itb.cif.gz mmcif
cp /home/sness/pdb/mmCIF/iw/3iwi.cif.gz mmcif
cp /home/sness/pdb/mmCIF/iw/3iwo.cif.gz mmcif
cp /home/sness/pdb/mmCIF/iw/3iwq.cif.gz mmcif
cp /home/sness/pdb/mmCIF/ix/3ixb.cif.gz mmcif
cp /home/sness/pdb/mmCIF/ix/3ixd.cif.gz mmcif
cp /home/sness/pdb/mmCIF/ix/3ixg.cif.gz mmcif
cp /home/sness/pdb/mmCIF/ix/3ixh.cif.gz mmcif
cp /home/sness/pdb/mmCIF/jy/3jyi.cif.gz mmcif
cp /home/sness/pdb/mmCIF/ky/3kye.cif.gz mmcif
cp /home/sness/pdb/mmCIF/lc/3lce.cif.gz mmcif
cp /home/sness/pdb/mmCIF/le/3leq.cif.gz mmcif
cp /home/sness/pdb/mmCIF/le/3lez.cif.gz mmcif
cp /home/sness/pdb/mmCIF/lo/3lo7.cif.gz mmcif
cp /home/sness/pdb/mmCIF/ly/3ly3.cif.gz mmcif
cp /home/sness/pdb/mmCIF/ly/3ly4.cif.gz mmcif
cp /home/sness/pdb/mmCIF/m2/3m2j.cif.gz mmcif
cp /home/sness/pdb/mmCIF/m2/3m2k.cif.gz mmcif
cp /home/sness/pdb/mmCIF/m6/3m6b.cif.gz mmcif
cp /home/sness/pdb/mmCIF/m6/3m6h.cif.gz mmcif
cp /home/sness/pdb/mmCIF/mb/3mbz.cif.gz mmcif
cp /home/sness/pdb/mmCIF/mf/3mfd.cif.gz mmcif
cp /home/sness/pdb/mmCIF/mk/3mke.cif.gz mmcif
cp /home/sness/pdb/mmCIF/mk/3mkf.cif.gz mmcif
cp /home/sness/pdb/mmCIF/mx/3mxr.cif.gz mmcif
cp /home/sness/pdb/mmCIF/mx/3mxs.cif.gz mmcif
cp /home/sness/pdb/mmCIF/mz/3mzd.cif.gz mmcif
cp /home/sness/pdb/mmCIF/mz/3mze.cif.gz mmcif
cp /home/sness/pdb/mmCIF/mz/3mzf.cif.gz mmcif
cp /home/sness/pdb/mmCIF/n4/3n4i.cif.gz mmcif
cp /home/sness/pdb/mmCIF/n6/3n6i.cif.gz mmcif
cp /home/sness/pdb/mmCIF/n7/3n7w.cif.gz mmcif
cp /home/sness/pdb/mmCIF/n8/3n8l.cif.gz mmcif
cp /home/sness/pdb/mmCIF/n8/3n8r.cif.gz mmcif
cp /home/sness/pdb/mmCIF/n8/3n8s.cif.gz mmcif
cp /home/sness/pdb/mmCIF/n9/3n91.cif.gz mmcif
cp /home/sness/pdb/mmCIF/nb/3nbl.cif.gz mmcif
cp /home/sness/pdb/mmCIF/nc/3nc8.cif.gz mmcif
cp /home/sness/pdb/mmCIF/nc/3nck.cif.gz mmcif
cp /home/sness/pdb/mmCIF/nd/3nde.cif.gz mmcif
cp /home/sness/pdb/mmCIF/nd/3ndg.cif.gz mmcif
cp /home/sness/pdb/mmCIF/ni/3ni9.cif.gz mmcif
cp /home/sness/pdb/mmCIF/ni/3nia.cif.gz mmcif
cp /home/sness/pdb/mmCIF/ny/3ny4.cif.gz mmcif
cp /home/sness/pdb/mmCIF/o5/3o5y.cif.gz mmcif
cp /home/sness/pdb/mmCIF/o8/3o86.cif.gz mmcif
cp /home/sness/pdb/mmCIF/o8/3o87.cif.gz mmcif
cp /home/sness/pdb/mmCIF/o8/3o88.cif.gz mmcif
cp /home/sness/pdb/mmCIF/oc/3oc2.cif.gz mmcif
cp /home/sness/pdb/mmCIF/oc/3ocl.cif.gz mmcif
cp /home/sness/pdb/mmCIF/oc/3ocn.cif.gz mmcif
cp /home/sness/pdb/mmCIF/oo/3oov.cif.gz mmcif
cp /home/sness/pdb/mmCIF/op/3oph.cif.gz mmcif
cp /home/sness/pdb/mmCIF/op/3opl.cif.gz mmcif
cp /home/sness/pdb/mmCIF/op/3opp.cif.gz mmcif
cp /home/sness/pdb/mmCIF/op/3opr.cif.gz mmcif
cp /home/sness/pdb/mmCIF/oz/3ozh.cif.gz mmcif
cp /home/sness/pdb/mmCIF/p0/3p09.cif.gz mmcif
cp /home/sness/pdb/mmCIF/p9/3p98.cif.gz mmcif
cp /home/sness/pdb/mmCIF/pa/3pae.cif.gz mmcif
cp /home/sness/pdb/mmCIF/pa/3pag.cif.gz mmcif
cp /home/sness/pdb/mmCIF/pb/3pbn.cif.gz mmcif
cp /home/sness/pdb/mmCIF/pb/3pbo.cif.gz mmcif
cp /home/sness/pdb/mmCIF/pb/3pbq.cif.gz mmcif
cp /home/sness/pdb/mmCIF/pb/3pbr.cif.gz mmcif
cp /home/sness/pdb/mmCIF/pb/3pbs.cif.gz mmcif
cp /home/sness/pdb/mmCIF/pb/3pbt.cif.gz mmcif
cp /home/sness/pdb/mmCIF/pt/3pte.cif.gz mmcif
cp /home/sness/pdb/mmCIF/q0/3q07.cif.gz mmcif
cp /home/sness/pdb/mmCIF/q1/3q1f.cif.gz mmcif
cp /home/sness/pdb/mmCIF/q7/3q7v.cif.gz mmcif
cp /home/sness/pdb/mmCIF/q7/3q7z.cif.gz mmcif
cp /home/sness/pdb/mmCIF/q8/3q81.cif.gz mmcif
cp /home/sness/pdb/mmCIF/q8/3q82.cif.gz mmcif
cp /home/sness/pdb/mmCIF/qh/3qhy.cif.gz mmcif
cp /home/sness/pdb/mmCIF/qn/3qnb.cif.gz mmcif
cp /home/sness/pdb/mmCIF/qn/3qnc.cif.gz mmcif
cp /home/sness/pdb/mmCIF/rj/3rju.cif.gz mmcif
cp /home/sness/pdb/mmCIF/rx/3rxw.cif.gz mmcif
cp /home/sness/pdb/mmCIF/rx/3rxx.cif.gz mmcif
cp /home/sness/pdb/mmCIF/s1/3s1y.cif.gz mmcif
cp /home/sness/pdb/mmCIF/s2/3s22.cif.gz mmcif
cp /home/sness/pdb/mmCIF/s4/3s4x.cif.gz mmcif
cp /home/sness/pdb/mmCIF/sh/3sh7.cif.gz mmcif
cp /home/sness/pdb/mmCIF/sh/3sh8.cif.gz mmcif
cp /home/sness/pdb/mmCIF/sh/3sh9.cif.gz mmcif
cp /home/sness/pdb/mmCIF/so/3soi.cif.gz mmcif
cp /home/sness/pdb/mmCIF/ss/3ss3.cif.gz mmcif
cp /home/sness/pdb/mmCIF/ss/3ss4.cif.gz mmcif
cp /home/sness/pdb/mmCIF/ss/3ss5.cif.gz mmcif
cp /home/sness/pdb/mmCIF/t1/3t12.cif.gz mmcif
cp /home/sness/pdb/mmCIF/t1/3t1q.cif.gz mmcif
cp /home/sness/pdb/mmCIF/t1/3t1r.cif.gz mmcif
cp /home/sness/pdb/mmCIF/t1/3t1s.cif.gz mmcif
cp /home/sness/pdb/mmCIF/t1/3t1x.cif.gz mmcif
cp /home/sness/pdb/mmCIF/tg/3tg9.cif.gz mmcif
cp /home/sness/pdb/mmCIF/to/3toi.cif.gz mmcif
cp /home/sness/pdb/mmCIF/tr/3trc.cif.gz mmcif
cp /home/sness/pdb/mmCIF/ts/3tsg.cif.gz mmcif
cp /home/sness/pdb/mmCIF/ud/3udf.cif.gz mmcif
cp /home/sness/pdb/mmCIF/ud/3udi.cif.gz mmcif
cp /home/sness/pdb/mmCIF/ud/3udx.cif.gz mmcif
cp /home/sness/pdb/mmCIF/ue/3ue0.cif.gz mmcif
cp /home/sness/pdb/mmCIF/ue/3ue1.cif.gz mmcif
cp /home/sness/pdb/mmCIF/ue/3ue3.cif.gz mmcif
cp /home/sness/pdb/mmCIF/un/3un7.cif.gz mmcif
cp /home/sness/pdb/mmCIF/un/3unw.cif.gz mmcif
cp /home/sness/pdb/mmCIF/uo/3uo9.cif.gz mmcif
cp /home/sness/pdb/mmCIF/up/3upn.cif.gz mmcif
cp /home/sness/pdb/mmCIF/up/3upo.cif.gz mmcif
cp /home/sness/pdb/mmCIF/up/3upp.cif.gz mmcif
cp /home/sness/pdb/mmCIF/uy/3uy6.cif.gz mmcif
cp /home/sness/pdb/mmCIF/v3/3v39.cif.gz mmcif
cp /home/sness/pdb/mmCIF/v3/3v3r.cif.gz mmcif
cp /home/sness/pdb/mmCIF/v3/3v3s.cif.gz mmcif
cp /home/sness/pdb/mmCIF/v5/3v50.cif.gz mmcif
cp /home/sness/pdb/mmCIF/v5/3v5m.cif.gz mmcif
cp /home/sness/pdb/mmCIF/vf/3vff.cif.gz mmcif
cp /home/sness/pdb/mmCIF/vf/3vfh.cif.gz mmcif
cp /home/sness/pdb/mmCIF/vm/3vma.cif.gz mmcif
cp /home/sness/pdb/mmCIF/vo/3voy.cif.gz mmcif
cp /home/sness/pdb/mmCIF/vo/3voz.cif.gz mmcif
cp /home/sness/pdb/mmCIF/vp/3vp0.cif.gz mmcif
cp /home/sness/pdb/mmCIF/vp/3vp1.cif.gz mmcif
cp /home/sness/pdb/mmCIF/vp/3vp2.cif.gz mmcif
cp /home/sness/pdb/mmCIF/vp/3vp3.cif.gz mmcif
cp /home/sness/pdb/mmCIF/vp/3vp4.cif.gz mmcif
cp /home/sness/pdb/mmCIF/vs/3vsk.cif.gz mmcif
cp /home/sness/pdb/mmCIF/vs/3vsl.cif.gz mmcif
cp /home/sness/pdb/mmCIF/vw/3vwn.cif.gz mmcif
cp /home/sness/pdb/mmCIF/w4/3w4o.cif.gz mmcif
cp /home/sness/pdb/mmCIF/w4/3w4p.cif.gz mmcif
cp /home/sness/pdb/mmCIF/w4/3w4q.cif.gz mmcif
cp /home/sness/pdb/mmCIF/w8/3w8k.cif.gz mmcif
cp /home/sness/pdb/mmCIF/wr/3wrt.cif.gz mmcif
cp /home/sness/pdb/mmCIF/wr/3wrz.cif.gz mmcif
cp /home/sness/pdb/mmCIF/ws/3ws0.cif.gz mmcif
cp /home/sness/pdb/mmCIF/ws/3ws1.cif.gz mmcif
cp /home/sness/pdb/mmCIF/ws/3ws2.cif.gz mmcif
cp /home/sness/pdb/mmCIF/ws/3ws4.cif.gz mmcif
cp /home/sness/pdb/mmCIF/ws/3ws5.cif.gz mmcif
cp /home/sness/pdb/mmCIF/ww/3wwx.cif.gz mmcif
cp /home/sness/pdb/mmCIF/zc/3zcz.cif.gz mmcif
cp /home/sness/pdb/mmCIF/zd/3zdj.cif.gz mmcif
cp /home/sness/pdb/mmCIF/zf/3zfz.cif.gz mmcif
cp /home/sness/pdb/mmCIF/zg/3zg0.cif.gz mmcif
cp /home/sness/pdb/mmCIF/zg/3zg5.cif.gz mmcif
cp /home/sness/pdb/mmCIF/zg/3zg9.cif.gz mmcif
cp /home/sness/pdb/mmCIF/zg/3zga.cif.gz mmcif
cp /home/sness/pdb/mmCIF/zh/3zhh.cif.gz mmcif
cp /home/sness/pdb/mmCIF/zn/3znt.cif.gz mmcif
cp /home/sness/pdb/mmCIF/zn/3zny.cif.gz mmcif
cp /home/sness/pdb/mmCIF/zv/3zvt.cif.gz mmcif
cp /home/sness/pdb/mmCIF/zv/3zvw.cif.gz mmcif
cp /home/sness/pdb/mmCIF/zy/3zyt.cif.gz mmcif
cp /home/sness/pdb/mmCIF/a5/4a5r.cif.gz mmcif
cp /home/sness/pdb/mmCIF/af/4afi.cif.gz mmcif
cp /home/sness/pdb/mmCIF/b8/4b88.cif.gz mmcif
cp /home/sness/pdb/mmCIF/b9/4b93.cif.gz mmcif
cp /home/sness/pdb/mmCIF/bd/4bd0.cif.gz mmcif
cp /home/sness/pdb/mmCIF/bd/4bd1.cif.gz mmcif
cp /home/sness/pdb/mmCIF/be/4ben.cif.gz mmcif
cp /home/sness/pdb/mmCIF/bj/4bjp.cif.gz mmcif
cp /home/sness/pdb/mmCIF/bl/4bl2.cif.gz mmcif
cp /home/sness/pdb/mmCIF/bl/4bl3.cif.gz mmcif
cp /home/sness/pdb/mmCIF/bl/4blm.cif.gz mmcif
cp /home/sness/pdb/mmCIF/bq/4bqm.cif.gz mmcif
cp /home/sness/pdb/mmCIF/c3/4c3q.cif.gz mmcif
cp /home/sness/pdb/mmCIF/c6/4c6y.cif.gz mmcif
cp /home/sness/pdb/mmCIF/c7/4c75.cif.gz mmcif
cp /home/sness/pdb/mmCIF/cj/4cjn.cif.gz mmcif
cp /home/sness/pdb/mmCIF/cl/4clc.cif.gz mmcif
cp /home/sness/pdb/mmCIF/cp/4cpk.cif.gz mmcif
cp /home/sness/pdb/mmCIF/d2/4d2o.cif.gz mmcif
cp /home/sness/pdb/mmCIF/df/4df6.cif.gz mmcif
cp /home/sness/pdb/mmCIF/dk/4dki.cif.gz mmcif
cp /home/sness/pdb/mmCIF/dr/4drt.cif.gz mmcif
cp /home/sness/pdb/mmCIF/dx/4dxb.cif.gz mmcif
cp /home/sness/pdb/mmCIF/dx/4dxc.cif.gz mmcif
cp /home/sness/pdb/mmCIF/e3/4e3i.cif.gz mmcif
cp /home/sness/pdb/mmCIF/e3/4e3j.cif.gz mmcif
cp /home/sness/pdb/mmCIF/e3/4e3k.cif.gz mmcif
cp /home/sness/pdb/mmCIF/e3/4e3l.cif.gz mmcif
cp /home/sness/pdb/mmCIF/e3/4e3m.cif.gz mmcif
cp /home/sness/pdb/mmCIF/e3/4e3n.cif.gz mmcif
cp /home/sness/pdb/mmCIF/e3/4e3o.cif.gz mmcif
cp /home/sness/pdb/mmCIF/e6/4e6w.cif.gz mmcif
cp /home/sness/pdb/mmCIF/e6/4e6x.cif.gz mmcif
cp /home/sness/pdb/mmCIF/eb/4ebl.cif.gz mmcif
cp /home/sness/pdb/mmCIF/eb/4ebn.cif.gz mmcif
cp /home/sness/pdb/mmCIF/eb/4ebp.cif.gz mmcif
cp /home/sness/pdb/mmCIF/eq/4eqi.cif.gz mmcif
cp /home/sness/pdb/mmCIF/eu/4euz.cif.gz mmcif
cp /home/sness/pdb/mmCIF/ev/4ev4.cif.gz mmcif
cp /home/sness/pdb/mmCIF/ew/4ewf.cif.gz mmcif
cp /home/sness/pdb/mmCIF/f9/4f94.cif.gz mmcif
cp /home/sness/pdb/mmCIF/fc/4fcf.cif.gz mmcif
cp /home/sness/pdb/mmCIF/fd/4fd8.cif.gz mmcif
cp /home/sness/pdb/mmCIF/fh/4fh2.cif.gz mmcif
cp /home/sness/pdb/mmCIF/fh/4fh4.cif.gz mmcif
cp /home/sness/pdb/mmCIF/fs/4fsf.cif.gz mmcif
cp /home/sness/pdb/mmCIF/gb/4gb7.cif.gz mmcif
cp /home/sness/pdb/mmCIF/gd/4gdn.cif.gz mmcif
cp /home/sness/pdb/mmCIF/gk/4gku.cif.gz mmcif
cp /home/sness/pdb/mmCIF/gz/4gzb.cif.gz mmcif
cp /home/sness/pdb/mmCIF/hb/4hbt.cif.gz mmcif
cp /home/sness/pdb/mmCIF/hb/4hbu.cif.gz mmcif
cp /home/sness/pdb/mmCIF/he/4hef.cif.gz mmcif
cp /home/sness/pdb/mmCIF/he/4hes.cif.gz mmcif
cp /home/sness/pdb/mmCIF/ib/4ibr.cif.gz mmcif
cp /home/sness/pdb/mmCIF/ib/4ibx.cif.gz mmcif
cp /home/sness/pdb/mmCIF/id/4id4.cif.gz mmcif
cp /home/sness/pdb/mmCIF/ie/4ied.cif.gz mmcif
cp /home/sness/pdb/mmCIF/iv/4ivi.cif.gz mmcif
cp /home/sness/pdb/mmCIF/iv/4ivk.cif.gz mmcif
cp /home/sness/pdb/mmCIF/jb/4jbf.cif.gz mmcif
cp /home/sness/pdb/mmCIF/jf/4jf4.cif.gz mmcif
cp /home/sness/pdb/mmCIF/jf/4jf5.cif.gz mmcif
cp /home/sness/pdb/mmCIF/jf/4jf6.cif.gz mmcif
cp /home/sness/pdb/mmCIF/jl/4jlf.cif.gz mmcif
cp /home/sness/pdb/mmCIF/jp/4jpm.cif.gz mmcif
cp /home/sness/pdb/mmCIF/jx/4jxg.cif.gz mmcif
cp /home/sness/pdb/mmCIF/jx/4jxs.cif.gz mmcif
cp /home/sness/pdb/mmCIF/jx/4jxv.cif.gz mmcif
cp /home/sness/pdb/mmCIF/jx/4jxw.cif.gz mmcif
cp /home/sness/pdb/mmCIF/k0/4k0x.cif.gz mmcif
cp /home/sness/pdb/mmCIF/k9/4k91.cif.gz mmcif
cp /home/sness/pdb/mmCIF/ke/4ken.cif.gz mmcif
cp /home/sness/pdb/mmCIF/kg/4kg2.cif.gz mmcif
cp /home/sness/pdb/mmCIF/kg/4kg5.cif.gz mmcif
cp /home/sness/pdb/mmCIF/kg/4kg6.cif.gz mmcif
cp /home/sness/pdb/mmCIF/kq/4kqq.cif.gz mmcif
cp /home/sness/pdb/mmCIF/kz/4kz3.cif.gz mmcif
cp /home/sness/pdb/mmCIF/kz/4kz4.cif.gz mmcif
cp /home/sness/pdb/mmCIF/kz/4kz5.cif.gz mmcif
cp /home/sness/pdb/mmCIF/kz/4kz6.cif.gz mmcif
cp /home/sness/pdb/mmCIF/kz/4kz7.cif.gz mmcif
cp /home/sness/pdb/mmCIF/kz/4kz8.cif.gz mmcif
cp /home/sness/pdb/mmCIF/kz/4kz9.cif.gz mmcif
cp /home/sness/pdb/mmCIF/kz/4kza.cif.gz mmcif
cp /home/sness/pdb/mmCIF/kz/4kzb.cif.gz mmcif
cp /home/sness/pdb/mmCIF/l0/4l0l.cif.gz mmcif
cp /home/sness/pdb/mmCIF/lc/4lcl.cif.gz mmcif
cp /home/sness/pdb/mmCIF/lc/4lcm.cif.gz mmcif
cp /home/sness/pdb/mmCIF/le/4len.cif.gz mmcif
cp /home/sness/pdb/mmCIF/lv/4lv0.cif.gz mmcif
cp /home/sness/pdb/mmCIF/lv/4lv1.cif.gz mmcif
cp /home/sness/pdb/mmCIF/lv/4lv2.cif.gz mmcif
cp /home/sness/pdb/mmCIF/lv/4lv3.cif.gz mmcif
cp /home/sness/pdb/mmCIF/m3/4m3k.cif.gz mmcif
cp /home/sness/pdb/mmCIF/mb/4mbf.cif.gz mmcif
cp /home/sness/pdb/mmCIF/mb/4mbh.cif.gz mmcif
cp /home/sness/pdb/mmCIF/mb/4mbk.cif.gz mmcif
cp /home/sness/pdb/mmCIF/me/4mez.cif.gz mmcif
cp /home/sness/pdb/mmCIF/ml/4mll.cif.gz mmcif
cp /home/sness/pdb/mmCIF/mn/4mnr.cif.gz mmcif
cp /home/sness/pdb/mmCIF/mx/4mx4.cif.gz mmcif
cp /home/sness/pdb/mmCIF/mx/4mxb.cif.gz mmcif
cp /home/sness/pdb/mmCIF/mx/4mxg.cif.gz mmcif
cp /home/sness/pdb/mmCIF/mx/4mxh.cif.gz mmcif
cp /home/sness/pdb/mmCIF/n1/4n1h.cif.gz mmcif
cp /home/sness/pdb/mmCIF/n1/4n1x.cif.gz mmcif
cp /home/sness/pdb/mmCIF/n9/4n92.cif.gz mmcif
cp /home/sness/pdb/mmCIF/n9/4n9k.cif.gz mmcif
cp /home/sness/pdb/mmCIF/n9/4n9l.cif.gz mmcif
cp /home/sness/pdb/mmCIF/ne/4net.cif.gz mmcif
cp /home/sness/pdb/mmCIF/o7/4o7d.cif.gz mmcif
cp /home/sness/pdb/mmCIF/oh/4oh0.cif.gz mmcif
cp /home/sness/pdb/mmCIF/ok/4okp.cif.gz mmcif
cp /home/sness/pdb/mmCIF/ol/4old.cif.gz mmcif
cp /home/sness/pdb/mmCIF/ol/4olg.cif.gz mmcif
cp /home/sness/pdb/mmCIF/oo/4ool.cif.gz mmcif
cp /home/sness/pdb/mmCIF/oo/4oom.cif.gz mmcif
cp /home/sness/pdb/mmCIF/oo/4oon.cif.gz mmcif
cp /home/sness/pdb/mmCIF/oo/4ooy.cif.gz mmcif
cp /home/sness/pdb/mmCIF/op/4op5.cif.gz mmcif
cp /home/sness/pdb/mmCIF/op/4op8.cif.gz mmcif
cp /home/sness/pdb/mmCIF/op/4opq.cif.gz mmcif
cp /home/sness/pdb/mmCIF/op/4opr.cif.gz mmcif
cp /home/sness/pdb/mmCIF/op/4opy.cif.gz mmcif
cp /home/sness/pdb/mmCIF/op/4opz.cif.gz mmcif
cp /home/sness/pdb/mmCIF/oq/4oq0.cif.gz mmcif
cp /home/sness/pdb/mmCIF/oq/4oqg.cif.gz mmcif
cp /home/sness/pdb/mmCIF/oq/4oqh.cif.gz mmcif
cp /home/sness/pdb/mmCIF/oq/4oqi.cif.gz mmcif
cp /home/sness/pdb/mmCIF/ov/4ovd.cif.gz mmcif
cp /home/sness/pdb/mmCIF/p0/4p0m.cif.gz mmcif
cp /home/sness/pdb/mmCIF/p6/4p6b.cif.gz mmcif
cp /home/sness/pdb/mmCIF/p8/4p85.cif.gz mmcif
cp /home/sness/pdb/mmCIF/p8/4p87.cif.gz mmcif
cp /home/sness/pdb/mmCIF/pm/4pm5.cif.gz mmcif
cp /home/sness/pdb/mmCIF/pm/4pm6.cif.gz mmcif
cp /home/sness/pdb/mmCIF/pm/4pm7.cif.gz mmcif
cp /home/sness/pdb/mmCIF/pm/4pm8.cif.gz mmcif
cp /home/sness/pdb/mmCIF/pm/4pm9.cif.gz mmcif
cp /home/sness/pdb/mmCIF/pm/4pma.cif.gz mmcif
cp /home/sness/pdb/mmCIF/pp/4ppr.cif.gz mmcif
cp /home/sness/pdb/mmCIF/q8/4q8i.cif.gz mmcif
cp /home/sness/pdb/mmCIF/qb/4qb8.cif.gz mmcif
cp /home/sness/pdb/mmCIF/qd/4qd4.cif.gz mmcif
cp /home/sness/pdb/mmCIF/qh/4qhc.cif.gz mmcif
cp /home/sness/pdb/mmCIF/qj/4qjg.cif.gz mmcif
cp /home/sness/pdb/mmCIF/qu/4qu3.cif.gz mmcif
cp /home/sness/pdb/mmCIF/qw/4qwo.cif.gz mmcif
cp /home/sness/pdb/mmCIF/qy/4qy5.cif.gz mmcif
cp /home/sness/pdb/mmCIF/qy/4qy6.cif.gz mmcif
cp /home/sness/pdb/mmCIF/r0/4r0q.cif.gz mmcif
cp /home/sness/pdb/mmCIF/r1/4r1g.cif.gz mmcif
cp /home/sness/pdb/mmCIF/r2/4r23.cif.gz mmcif
cp /home/sness/pdb/mmCIF/r3/4r3b.cif.gz mmcif
cp /home/sness/pdb/mmCIF/r3/4r3j.cif.gz mmcif
cp /home/sness/pdb/mmCIF/r4/4r4r.cif.gz mmcif
cp /home/sness/pdb/mmCIF/r4/4r4s.cif.gz mmcif
cp /home/sness/pdb/mmCIF/ra/4ra7.cif.gz mmcif
cp /home/sness/pdb/mmCIF/rv/4rva.cif.gz mmcif
cp /home/sness/pdb/mmCIF/rx/4rx2.cif.gz mmcif
cp /home/sness/pdb/mmCIF/rx/4rx3.cif.gz mmcif
cp /home/sness/pdb/mmCIF/ry/4rye.cif.gz mmcif
cp /home/sness/pdb/mmCIF/s2/4s2i.cif.gz mmcif
cp /home/sness/pdb/mmCIF/s2/4s2j.cif.gz mmcif
cp /home/sness/pdb/mmCIF/s2/4s2k.cif.gz mmcif
cp /home/sness/pdb/mmCIF/s2/4s2l.cif.gz mmcif
cp /home/sness/pdb/mmCIF/s2/4s2m.cif.gz mmcif
cp /home/sness/pdb/mmCIF/s2/4s2n.cif.gz mmcif
cp /home/sness/pdb/mmCIF/s2/4s2o.cif.gz mmcif
cp /home/sness/pdb/mmCIF/s2/4s2p.cif.gz mmcif
cp /home/sness/pdb/mmCIF/u0/4u0t.cif.gz mmcif
cp /home/sness/pdb/mmCIF/u0/4u0x.cif.gz mmcif
cp /home/sness/pdb/mmCIF/u3/4u3t.cif.gz mmcif
cp /home/sness/pdb/mmCIF/ua/4ua6.cif.gz mmcif
cp /home/sness/pdb/mmCIF/ua/4ua7.cif.gz mmcif
cp /home/sness/pdb/mmCIF/ua/4ua9.cif.gz mmcif
cp /home/sness/pdb/mmCIF/ua/4uaa.cif.gz mmcif
cp /home/sness/pdb/mmCIF/uh/4uhu.cif.gz mmcif
cp /home/sness/pdb/mmCIF/wb/4wbg.cif.gz mmcif
cp /home/sness/pdb/mmCIF/we/4wej.cif.gz mmcif
cp /home/sness/pdb/mmCIF/we/4wek.cif.gz mmcif
cp /home/sness/pdb/mmCIF/we/4wel.cif.gz mmcif
cp /home/sness/pdb/mmCIF/wm/4wm9.cif.gz mmcif
cp /home/sness/pdb/mmCIF/wm/4wmc.cif.gz mmcif
cp /home/sness/pdb/mmCIF/wy/4wyy.cif.gz mmcif
cp /home/sness/pdb/mmCIF/wz/4wz4.cif.gz mmcif
cp /home/sness/pdb/mmCIF/wz/4wz5.cif.gz mmcif
cp /home/sness/pdb/mmCIF/x5/4x53.cif.gz mmcif
cp /home/sness/pdb/mmCIF/x5/4x55.cif.gz mmcif
cp /home/sness/pdb/mmCIF/x5/4x56.cif.gz mmcif
cp /home/sness/pdb/mmCIF/x6/4x68.cif.gz mmcif
cp /home/sness/pdb/mmCIF/x6/4x69.cif.gz mmcif
cp /home/sness/pdb/mmCIF/x6/4x6t.cif.gz mmcif
cp /home/sness/pdb/mmCIF/xu/4xux.cif.gz mmcif
cp /home/sness/pdb/mmCIF/xu/4xuz.cif.gz mmcif
cp /home/sness/pdb/mmCIF/xx/4xxr.cif.gz mmcif
cp /home/sness/pdb/mmCIF/y0/4y0o.cif.gz mmcif
cp /home/sness/pdb/mmCIF/y0/4y0t.cif.gz mmcif
cp /home/sness/pdb/mmCIF/y0/4y0u.cif.gz mmcif
cp /home/sness/pdb/mmCIF/y7/4y7p.cif.gz mmcif
cp /home/sness/pdb/mmCIF/ye/4ye5.cif.gz mmcif
cp /home/sness/pdb/mmCIF/yf/4yfm.cif.gz mmcif
cp /home/sness/pdb/mmCIF/yi/4yin.cif.gz mmcif
cp /home/sness/pdb/mmCIF/z9/4z9q.cif.gz mmcif
cp /home/sness/pdb/mmCIF/za/4zam.cif.gz mmcif
cp /home/sness/pdb/mmCIF/zb/4zbe.cif.gz mmcif
cp /home/sness/pdb/mmCIF/zd/4zdx.cif.gz mmcif
cp /home/sness/pdb/mmCIF/zj/4zj1.cif.gz mmcif
cp /home/sness/pdb/mmCIF/zj/4zj2.cif.gz mmcif
cp /home/sness/pdb/mmCIF/zj/4zj3.cif.gz mmcif
cp /home/sness/pdb/mmCIF/zt/4ztk.cif.gz mmcif
cp /home/sness/pdb/mmCIF/a9/5a90.cif.gz mmcif
cp /home/sness/pdb/mmCIF/a9/5a91.cif.gz mmcif
cp /home/sness/pdb/mmCIF/a9/5a92.cif.gz mmcif
cp /home/sness/pdb/mmCIF/a9/5a93.cif.gz mmcif
cp /home/sness/pdb/mmCIF/aq/5aq7.cif.gz mmcif
cp /home/sness/pdb/mmCIF/aq/5aq8.cif.gz mmcif
cp /home/sness/pdb/mmCIF/aq/5aq9.cif.gz mmcif
cp /home/sness/pdb/mmCIF/aq/5aqa.cif.gz mmcif
cp /home/sness/pdb/mmCIF/aq/5aqb.cif.gz mmcif
cp /home/sness/pdb/mmCIF/bo/5boh.cif.gz mmcif
cp /home/sness/pdb/mmCIF/ce/5ceb.cif.gz mmcif
cp /home/sness/pdb/mmCIF/ce/5cec.cif.gz mmcif
cp /home/sness/pdb/mmCIF/ce/5ced.cif.gz mmcif
cp /home/sness/pdb/mmCIF/ce/5cer.cif.gz mmcif
cp /home/sness/pdb/mmCIF/cg/5cgs.cif.gz mmcif
cp /home/sness/pdb/mmCIF/cg/5cgw.cif.gz mmcif
cp /home/sness/pdb/mmCIF/cg/5cgx.cif.gz mmcif
cp /home/sness/pdb/mmCIF/ch/5chj.cif.gz mmcif
cp /home/sness/pdb/mmCIF/ch/5chm.cif.gz mmcif
cp /home/sness/pdb/mmCIF/ch/5chu.cif.gz mmcif
cp /home/sness/pdb/mmCIF/cr/5crf.cif.gz mmcif
cp /home/sness/pdb/mmCIF/ct/5ctm.cif.gz mmcif
cp /home/sness/pdb/mmCIF/ct/5ctn.cif.gz mmcif
cp /home/sness/pdb/mmCIF/cx/5cxw.cif.gz mmcif
cp /home/sness/pdb/mmCIF/d3/5d3o.cif.gz mmcif
cp /home/sness/pdb/mmCIF/df/5df7.cif.gz mmcif
cp /home/sness/pdb/mmCIF/df/5df8.cif.gz mmcif
cp /home/sness/pdb/mmCIF/df/5df9.cif.gz mmcif
cp /home/sness/pdb/mmCIF/df/5dfx.cif.gz mmcif
cp /home/sness/pdb/mmCIF/dt/5dtk.cif.gz mmcif
cp /home/sness/pdb/mmCIF/dt/5dts.cif.gz mmcif
cp /home/sness/pdb/mmCIF/dt/5dtt.cif.gz mmcif
cp /home/sness/pdb/mmCIF/dv/5dva.cif.gz mmcif
cp /home/sness/pdb/mmCIF/dv/5dvy.cif.gz mmcif
cp /home/sness/pdb/mmCIF/e2/5e2e.cif.gz mmcif
cp /home/sness/pdb/mmCIF/e2/5e2f.cif.gz mmcif
cp /home/sness/pdb/mmCIF/e2/5e2g.cif.gz mmcif
cp /home/sness/pdb/mmCIF/e2/5e2h.cif.gz mmcif
cp /home/sness/pdb/mmCIF/e3/5e31.cif.gz mmcif
cp /home/sness/pdb/mmCIF/e4/5e43.cif.gz mmcif
cp /home/sness/pdb/mmCIF/ee/5ee8.cif.gz mmcif
cp /home/sness/pdb/mmCIF/ee/5eec.cif.gz mmcif
cp /home/sness/pdb/mmCIF/eo/5eoe.cif.gz mmcif
cp /home/sness/pdb/mmCIF/eo/5eoo.cif.gz mmcif
cp /home/sness/pdb/mmCIF/ep/5eph.cif.gz mmcif
cp /home/sness/pdb/mmCIF/eu/5eua.cif.gz mmcif
cp /home/sness/pdb/mmCIF/ev/5evi.cif.gz mmcif
cp /home/sness/pdb/mmCIF/ev/5evl.cif.gz mmcif
cp /home/sness/pdb/mmCIF/f1/5f1f.cif.gz mmcif
cp /home/sness/pdb/mmCIF/f1/5f1g.cif.gz mmcif
cp /home/sness/pdb/mmCIF/f8/5f82.cif.gz mmcif
cp /home/sness/pdb/mmCIF/f8/5f83.cif.gz mmcif
cp /home/sness/pdb/mmCIF/fa/5fa7.cif.gz mmcif
cp /home/sness/pdb/mmCIF/fa/5fao.cif.gz mmcif
cp /home/sness/pdb/mmCIF/fa/5fap.cif.gz mmcif
cp /home/sness/pdb/mmCIF/fa/5faq.cif.gz mmcif
cp /home/sness/pdb/mmCIF/fa/5fas.cif.gz mmcif
cp /home/sness/pdb/mmCIF/fa/5fat.cif.gz mmcif
cp /home/sness/pdb/mmCIF/fd/5fdh.cif.gz mmcif
cp /home/sness/pdb/mmCIF/fg/5fgz.cif.gz mmcif
cp /home/sness/pdb/mmCIF/fi/5fi2.cif.gz mmcif
cp /home/sness/pdb/mmCIF/fi/5fi6.cif.gz mmcif
cp /home/sness/pdb/mmCIF/fi/5fi7.cif.gz mmcif
cp /home/sness/pdb/mmCIF/fq/5fq9.cif.gz mmcif
cp /home/sness/pdb/mmCIF/fq/5fqi.cif.gz mmcif
cp /home/sness/pdb/mmCIF/fq/5fqj.cif.gz mmcif
cp /home/sness/pdb/mmCIF/fq/5fqk.cif.gz mmcif
cp /home/sness/pdb/mmCIF/fq/5fqm.cif.gz mmcif
cp /home/sness/pdb/mmCIF/fq/5fqq.cif.gz mmcif
cp /home/sness/pdb/mmCIF/fs/5fsr.cif.gz mmcif
cp /home/sness/pdb/mmCIF/g1/5g18.cif.gz mmcif
cp /home/sness/pdb/mmCIF/gg/5ggw.cif.gz mmcif
cp /home/sness/pdb/mmCIF/gh/5ghx.cif.gz mmcif
cp /home/sness/pdb/mmCIF/gh/5ghy.cif.gz mmcif
cp /home/sness/pdb/mmCIF/gh/5ghz.cif.gz mmcif
cp /home/sness/pdb/mmCIF/gk/5gkv.cif.gz mmcif
cp /home/sness/pdb/mmCIF/gl/5gl9.cif.gz mmcif
cp /home/sness/pdb/mmCIF/gl/5gla.cif.gz mmcif
cp /home/sness/pdb/mmCIF/gl/5glb.cif.gz mmcif
cp /home/sness/pdb/mmCIF/gl/5glc.cif.gz mmcif
cp /home/sness/pdb/mmCIF/gl/5gld.cif.gz mmcif
cp /home/sness/pdb/mmCIF/gm/5gmx.cif.gz mmcif
cp /home/sness/pdb/mmCIF/gs/5gs8.cif.gz mmcif
cp /home/sness/pdb/mmCIF/gs/5gsc.cif.gz mmcif
cp /home/sness/pdb/mmCIF/gw/5gwa.cif.gz mmcif
cp /home/sness/pdb/mmCIF/gz/5gzw.cif.gz mmcif
cp /home/sness/pdb/mmCIF/ha/5hai.cif.gz mmcif
cp /home/sness/pdb/mmCIF/ha/5hap.cif.gz mmcif
cp /home/sness/pdb/mmCIF/ha/5haq.cif.gz mmcif
cp /home/sness/pdb/mmCIF/ha/5har.cif.gz mmcif
cp /home/sness/pdb/mmCIF/hf/5hfo.cif.gz mmcif
cp /home/sness/pdb/mmCIF/hl/5hl1.cif.gz mmcif
cp /home/sness/pdb/mmCIF/hl/5hl9.cif.gz mmcif
cp /home/sness/pdb/mmCIF/hl/5hla.cif.gz mmcif
cp /home/sness/pdb/mmCIF/hl/5hlb.cif.gz mmcif
cp /home/sness/pdb/mmCIF/hl/5hld.cif.gz mmcif
cp /home/sness/pdb/mmCIF/hv/5hvi.cif.gz mmcif
cp /home/sness/pdb/mmCIF/hw/5hw1.cif.gz mmcif
cp /home/sness/pdb/mmCIF/hw/5hw3.cif.gz mmcif
cp /home/sness/pdb/mmCIF/hw/5hw5.cif.gz mmcif
cp /home/sness/pdb/mmCIF/hx/5hx9.cif.gz mmcif
cp /home/sness/pdb/mmCIF/hz/5hzi.cif.gz mmcif
cp /home/sness/pdb/mmCIF/i5/5i52.cif.gz mmcif
cp /home/sness/pdb/mmCIF/i6/5i63.cif.gz mmcif
cp /home/sness/pdb/mmCIF/i9/5i94.cif.gz mmcif
cp /home/sness/pdb/mmCIF/ih/5ihv.cif.gz mmcif
cp /home/sness/pdb/mmCIF/iq/5iq8.cif.gz mmcif
cp /home/sness/pdb/mmCIF/iy/5iy2.cif.gz mmcif
cp /home/sness/pdb/mmCIF/j8/5j8x.cif.gz mmcif
cp /home/sness/pdb/mmCIF/jo/5joc.cif.gz mmcif
cp /home/sness/pdb/mmCIF/jy/5jyo.cif.gz mmcif
cp /home/sness/pdb/mmCIF/jy/5jyp.cif.gz mmcif
cp /home/sness/pdb/mmCIF/k1/5k1d.cif.gz mmcif
cp /home/sness/pdb/mmCIF/k1/5k1f.cif.gz mmcif
cp /home/sness/pdb/mmCIF/kk/5kkf.cif.gz mmcif
cp /home/sness/pdb/mmCIF/km/5kmt.cif.gz mmcif
cp /home/sness/pdb/mmCIF/km/5kmu.cif.gz mmcif
cp /home/sness/pdb/mmCIF/km/5kmw.cif.gz mmcif
cp /home/sness/pdb/mmCIF/kp/5kpu.cif.gz mmcif
cp /home/sness/pdb/mmCIF/ks/5ksc.cif.gz mmcif
cp /home/sness/pdb/mmCIF/ks/5ksh.cif.gz mmcif
cp /home/sness/pdb/mmCIF/kz/5kzh.cif.gz mmcif
cp /home/sness/pdb/mmCIF/l0/5l07.cif.gz mmcif
cp /home/sness/pdb/mmCIF/l0/5l09.cif.gz mmcif
cp /home/sness/pdb/mmCIF/l2/5l2f.cif.gz mmcif
cp /home/sness/pdb/mmCIF/ld/5ldd.cif.gz mmcif
cp /home/sness/pdb/mmCIF/ll/5ll7.cif.gz mmcif
cp /home/sness/pdb/mmCIF/ll/5llw.cif.gz mmcif
cp /home/sness/pdb/mmCIF/lo/5loe.cif.gz mmcif
cp /home/sness/pdb/mmCIF/lp/5lp4.cif.gz mmcif
cp /home/sness/pdb/mmCIF/lp/5lp5.cif.gz mmcif
cp /home/sness/pdb/mmCIF/lw/5lwf.cif.gz mmcif
cp /home/sness/pdb/mmCIF/m1/5m18.cif.gz mmcif
cp /home/sness/pdb/mmCIF/m1/5m19.cif.gz mmcif
cp /home/sness/pdb/mmCIF/m1/5m1a.cif.gz mmcif
cp /home/sness/pdb/mmCIF/m4/5m45.cif.gz mmcif
cp /home/sness/pdb/mmCIF/mg/5mgi.cif.gz mmcif
cp /home/sness/pdb/mmCIF/mm/5mmj.cif.gz mmcif
cp /home/sness/pdb/mmCIF/mm/5mmy.cif.gz mmcif
cp /home/sness/pdb/mmCIF/mn/5mnu.cif.gz mmcif
cp /home/sness/pdb/mmCIF/mo/5mox.cif.gz mmcif
cp /home/sness/pdb/mmCIF/mo/5moz.cif.gz mmcif
cp /home/sness/pdb/mmCIF/n0/5n0l.cif.gz mmcif
cp /home/sness/pdb/mmCIF/ne/5ne1.cif.gz mmcif
cp /home/sness/pdb/mmCIF/ne/5ne2.cif.gz mmcif
cp /home/sness/pdb/mmCIF/ne/5ne3.cif.gz mmcif
cp /home/sness/pdb/mmCIF/nj/5nj2.cif.gz mmcif
cp /home/sness/pdb/mmCIF/np/5npo.cif.gz mmcif
cp /home/sness/pdb/mmCIF/nv/5nvs.cif.gz mmcif
cp /home/sness/pdb/mmCIF/nw/5nw4.cif.gz mmcif
cp /home/sness/pdb/mmCIF/od/5odz.cif.gz mmcif
cp /home/sness/pdb/mmCIF/oe/5oe0.cif.gz mmcif
cp /home/sness/pdb/mmCIF/oe/5oe2.cif.gz mmcif
cp /home/sness/pdb/mmCIF/of/5oft.cif.gz mmcif
cp /home/sness/pdb/mmCIF/oj/5oj0.cif.gz mmcif
cp /home/sness/pdb/mmCIF/oy/5oyo.cif.gz mmcif
cp /home/sness/pdb/mmCIF/qa/5qa4.cif.gz mmcif
cp /home/sness/pdb/mmCIF/qa/5qa5.cif.gz mmcif
cp /home/sness/pdb/mmCIF/qa/5qa6.cif.gz mmcif
cp /home/sness/pdb/mmCIF/qa/5qa7.cif.gz mmcif
cp /home/sness/pdb/mmCIF/qa/5qa8.cif.gz mmcif
cp /home/sness/pdb/mmCIF/qa/5qa9.cif.gz mmcif
cp /home/sness/pdb/mmCIF/qa/5qaa.cif.gz mmcif
cp /home/sness/pdb/mmCIF/qa/5qab.cif.gz mmcif
cp /home/sness/pdb/mmCIF/qa/5qac.cif.gz mmcif
cp /home/sness/pdb/mmCIF/qa/5qad.cif.gz mmcif
cp /home/sness/pdb/mmCIF/qa/5qae.cif.gz mmcif
cp /home/sness/pdb/mmCIF/qa/5qaf.cif.gz mmcif
cp /home/sness/pdb/mmCIF/qa/5qag.cif.gz mmcif
cp /home/sness/pdb/mmCIF/qa/5qah.cif.gz mmcif
cp /home/sness/pdb/mmCIF/qa/5qai.cif.gz mmcif
cp /home/sness/pdb/mmCIF/qa/5qaj.cif.gz mmcif
cp /home/sness/pdb/mmCIF/qa/5qak.cif.gz mmcif
cp /home/sness/pdb/mmCIF/qa/5qal.cif.gz mmcif
cp /home/sness/pdb/mmCIF/qa/5qam.cif.gz mmcif
cp /home/sness/pdb/mmCIF/qa/5qan.cif.gz mmcif
cp /home/sness/pdb/mmCIF/qa/5qao.cif.gz mmcif
cp /home/sness/pdb/mmCIF/qa/5qap.cif.gz mmcif
cp /home/sness/pdb/mmCIF/qa/5qaq.cif.gz mmcif
cp /home/sness/pdb/mmCIF/qa/5qar.cif.gz mmcif
cp /home/sness/pdb/mmCIF/qa/5qas.cif.gz mmcif
cp /home/sness/pdb/mmCIF/qa/5qat.cif.gz mmcif
cp /home/sness/pdb/mmCIF/qa/5qau.cif.gz mmcif
cp /home/sness/pdb/mmCIF/qa/5qav.cif.gz mmcif
cp /home/sness/pdb/mmCIF/qa/5qaw.cif.gz mmcif
cp /home/sness/pdb/mmCIF/qa/5qax.cif.gz mmcif
cp /home/sness/pdb/mmCIF/qa/5qay.cif.gz mmcif
cp /home/sness/pdb/mmCIF/qa/5qaz.cif.gz mmcif
cp /home/sness/pdb/mmCIF/qb/5qb0.cif.gz mmcif
cp /home/sness/pdb/mmCIF/qb/5qb1.cif.gz mmcif
cp /home/sness/pdb/mmCIF/qb/5qb2.cif.gz mmcif
cp /home/sness/pdb/mmCIF/qb/5qb3.cif.gz mmcif
cp /home/sness/pdb/mmCIF/qb/5qb4.cif.gz mmcif
cp /home/sness/pdb/mmCIF/sv/5svc.cif.gz mmcif
cp /home/sness/pdb/mmCIF/t6/5t66.cif.gz mmcif
cp /home/sness/pdb/mmCIF/tf/5tfq.cif.gz mmcif
cp /home/sness/pdb/mmCIF/tg/5tg4.cif.gz mmcif
cp /home/sness/pdb/mmCIF/tg/5tg5.cif.gz mmcif
cp /home/sness/pdb/mmCIF/tg/5tg6.cif.gz mmcif
cp /home/sness/pdb/mmCIF/tg/5tg7.cif.gz mmcif
cp /home/sness/pdb/mmCIF/tg/5tgf.cif.gz mmcif
cp /home/sness/pdb/mmCIF/tj/5tjj.cif.gz mmcif
cp /home/sness/pdb/mmCIF/to/5top.cif.gz mmcif
cp /home/sness/pdb/mmCIF/to/5toy.cif.gz mmcif
cp /home/sness/pdb/mmCIF/tr/5tr7.cif.gz mmcif
cp /home/sness/pdb/mmCIF/tr/5tro.cif.gz mmcif
cp /home/sness/pdb/mmCIF/tw/5tw4.cif.gz mmcif
cp /home/sness/pdb/mmCIF/tw/5tw6.cif.gz mmcif
cp /home/sness/pdb/mmCIF/tw/5tw8.cif.gz mmcif
cp /home/sness/pdb/mmCIF/tw/5twd.cif.gz mmcif
cp /home/sness/pdb/mmCIF/tw/5twe.cif.gz mmcif
cp /home/sness/pdb/mmCIF/tx/5tx9.cif.gz mmcif
cp /home/sness/pdb/mmCIF/tx/5txi.cif.gz mmcif
cp /home/sness/pdb/mmCIF/ty/5ty2.cif.gz mmcif
cp /home/sness/pdb/mmCIF/ty/5ty7.cif.gz mmcif
cp /home/sness/pdb/mmCIF/u2/5u2g.cif.gz mmcif
cp /home/sness/pdb/mmCIF/u4/5u47.cif.gz mmcif
cp /home/sness/pdb/mmCIF/u5/5u53.cif.gz mmcif
cp /home/sness/pdb/mmCIF/uj/5uj3.cif.gz mmcif
cp /home/sness/pdb/mmCIF/uj/5uj4.cif.gz mmcif
cp /home/sness/pdb/mmCIF/uj/5ujo.cif.gz mmcif
cp /home/sness/pdb/mmCIF/ul/5ul8.cif.gz mmcif
cp /home/sness/pdb/mmCIF/uq/5uqe.cif.gz mmcif
cp /home/sness/pdb/mmCIF/uy/5uy7.cif.gz mmcif
cp /home/sness/pdb/mmCIF/vf/5vfd.cif.gz mmcif
cp /home/sness/pdb/mmCIF/vl/5vle.cif.gz mmcif
cp /home/sness/pdb/mmCIF/vp/5vpq.cif.gz mmcif
cp /home/sness/pdb/mmCIF/vt/5vth.cif.gz mmcif
cp /home/sness/pdb/mmCIF/w1/5w12.cif.gz mmcif
cp /home/sness/pdb/mmCIF/w1/5w13.cif.gz mmcif
cp /home/sness/pdb/mmCIF/w1/5w14.cif.gz mmcif
cp /home/sness/pdb/mmCIF/w2/5w2j.cif.gz mmcif
cp /home/sness/pdb/mmCIF/wa/5wac.cif.gz mmcif
cp /home/sness/pdb/mmCIF/wa/5wad.cif.gz mmcif
cp /home/sness/pdb/mmCIF/wa/5wae.cif.gz mmcif
cp /home/sness/pdb/mmCIF/wa/5waf.cif.gz mmcif
cp /home/sness/pdb/mmCIF/wa/5wag.cif.gz mmcif
cp /home/sness/pdb/mmCIF/wh/5whm.cif.gz mmcif
cp /home/sness/pdb/mmCIF/wi/5wi3.cif.gz mmcif
cp /home/sness/pdb/mmCIF/wi/5wi7.cif.gz mmcif
cp /home/sness/pdb/mmCIF/wi/5wib.cif.gz mmcif
cp /home/sness/pdb/mmCIF/wj/5wj6.cif.gz mmcif
cp /home/sness/pdb/mmCIF/x5/5x5g.cif.gz mmcif
cp /home/sness/pdb/mmCIF/x6/5x6u.cif.gz mmcif
cp /home/sness/pdb/mmCIF/xh/5xhr.cif.gz mmcif
cp /home/sness/pdb/mmCIF/za/5za2.cif.gz mmcif
cp /home/sness/pdb/mmCIF/zb/5zb7.cif.gz mmcif
cp /home/sness/pdb/mmCIF/zf/5zfl.cif.gz mmcif
cp /home/sness/pdb/mmCIF/zf/5zft.cif.gz mmcif
cp /home/sness/pdb/mmCIF/zg/5zg6.cif.gz mmcif
cp /home/sness/pdb/mmCIF/zh/5zh8.cif.gz mmcif
cp /home/sness/pdb/mmCIF/zq/5zqa.cif.gz mmcif
cp /home/sness/pdb/mmCIF/zq/5zqb.cif.gz mmcif
cp /home/sness/pdb/mmCIF/zq/5zqc.cif.gz mmcif
cp /home/sness/pdb/mmCIF/zq/5zqd.cif.gz mmcif
cp /home/sness/pdb/mmCIF/zq/5zqe.cif.gz mmcif
cp /home/sness/pdb/mmCIF/zw/5zwq.cif.gz mmcif
cp /home/sness/pdb/mmCIF/zw/5zwr.cif.gz mmcif
cp /home/sness/pdb/mmCIF/zw/5zwv.cif.gz mmcif
cp /home/sness/pdb/mmCIF/zy/5zyb.cif.gz mmcif
cp /home/sness/pdb/mmCIF/zz/5zzb.cif.gz mmcif
cp /home/sness/pdb/mmCIF/af/6afm.cif.gz mmcif
cp /home/sness/pdb/mmCIF/af/6afn.cif.gz mmcif
cp /home/sness/pdb/mmCIF/af/6afo.cif.gz mmcif
cp /home/sness/pdb/mmCIF/af/6afp.cif.gz mmcif
cp /home/sness/pdb/mmCIF/ap/6apa.cif.gz mmcif
cp /home/sness/pdb/mmCIF/ay/6ayk.cif.gz mmcif
cp /home/sness/pdb/mmCIF/az/6azi.cif.gz mmcif
cp /home/sness/pdb/mmCIF/b1/6b1f.cif.gz mmcif
cp /home/sness/pdb/mmCIF/b1/6b1h.cif.gz mmcif
cp /home/sness/pdb/mmCIF/b1/6b1j.cif.gz mmcif
cp /home/sness/pdb/mmCIF/b1/6b1w.cif.gz mmcif
cp /home/sness/pdb/mmCIF/b1/6b1x.cif.gz mmcif
cp /home/sness/pdb/mmCIF/b1/6b1y.cif.gz mmcif
cp /home/sness/pdb/mmCIF/b2/6b22.cif.gz mmcif
cp /home/sness/pdb/mmCIF/b2/6b2n.cif.gz mmcif
cp /home/sness/pdb/mmCIF/b5/6b5x.cif.gz mmcif
cp /home/sness/pdb/mmCIF/b5/6b5y.cif.gz mmcif
cp /home/sness/pdb/mmCIF/b6/6b68.cif.gz mmcif
cp /home/sness/pdb/mmCIF/b6/6b69.cif.gz mmcif
cp /home/sness/pdb/mmCIF/b6/6b6a.cif.gz mmcif
cp /home/sness/pdb/mmCIF/b6/6b6b.cif.gz mmcif
cp /home/sness/pdb/mmCIF/b6/6b6c.cif.gz mmcif
cp /home/sness/pdb/mmCIF/b6/6b6d.cif.gz mmcif
cp /home/sness/pdb/mmCIF/b6/6b6e.cif.gz mmcif
cp /home/sness/pdb/mmCIF/b6/6b6f.cif.gz mmcif
cp /home/sness/pdb/mmCIF/b9/6b9x.cif.gz mmcif
cp /home/sness/pdb/mmCIF/bn/6bn3.cif.gz mmcif
cp /home/sness/pdb/mmCIF/bp/6bpf.cif.gz mmcif
cp /home/sness/pdb/mmCIF/bs/6bsq.cif.gz mmcif
cp /home/sness/pdb/mmCIF/bs/6bsr.cif.gz mmcif
cp /home/sness/pdb/mmCIF/bt/6bt6.cif.gz mmcif
cp /home/sness/pdb/mmCIF/bu/6bu3.cif.gz mmcif
cp /home/sness/pdb/mmCIF/c3/6c39.cif.gz mmcif
cp /home/sness/pdb/mmCIF/c3/6c3k.cif.gz mmcif
cp /home/sness/pdb/mmCIF/c7/6c78.cif.gz mmcif
cp /home/sness/pdb/mmCIF/c7/6c79.cif.gz mmcif
cp /home/sness/pdb/mmCIF/c7/6c7a.cif.gz mmcif
cp /home/sness/pdb/mmCIF/c8/6c84.cif.gz mmcif
cp /home/sness/pdb/mmCIF/ce/6ces.cif.gz mmcif
cp /home/sness/pdb/mmCIF/cy/6cyk.cif.gz mmcif
cp /home/sness/pdb/mmCIF/cy/6cyn.cif.gz mmcif
cp /home/sness/pdb/mmCIF/cy/6cyq.cif.gz mmcif
cp /home/sness/pdb/mmCIF/cy/6cyu.cif.gz mmcif
cp /home/sness/pdb/mmCIF/d1/6d15.cif.gz mmcif
cp /home/sness/pdb/mmCIF/d1/6d16.cif.gz mmcif
cp /home/sness/pdb/mmCIF/d1/6d17.cif.gz mmcif
cp /home/sness/pdb/mmCIF/d1/6d18.cif.gz mmcif
cp /home/sness/pdb/mmCIF/d1/6d19.cif.gz mmcif
cp /home/sness/pdb/mmCIF/d3/6d3g.cif.gz mmcif
cp /home/sness/pdb/mmCIF/d7/6d7h.cif.gz mmcif
cp /home/sness/pdb/mmCIF/d7/6d7i.cif.gz mmcif
cp /home/sness/pdb/mmCIF/dg/6dgu.cif.gz mmcif
cp /home/sness/pdb/mmCIF/dm/6dmh.cif.gz mmcif
cp /home/sness/pdb/mmCIF/dp/6dpt.cif.gz mmcif
cp /home/sness/pdb/mmCIF/dp/6dpx.cif.gz mmcif
cp /home/sness/pdb/mmCIF/dp/6dpy.cif.gz mmcif
cp /home/sness/pdb/mmCIF/dp/6dpz.cif.gz mmcif
cp /home/sness/pdb/mmCIF/dz/6dz8.cif.gz mmcif
cp /home/sness/pdb/mmCIF/ed/6edm.cif.gz mmcif
cp /home/sness/pdb/mmCIF/eh/6ehp.cif.gz mmcif
cp /home/sness/pdb/mmCIF/eh/6ehr.cif.gz mmcif
cp /home/sness/pdb/mmCIF/fm/6fm6.cif.gz mmcif
cp /home/sness/pdb/mmCIF/ft/6ftd.cif.gz mmcif
cp /home/sness/pdb/mmCIF/g0/6g0k.cif.gz mmcif
cp /home/sness/pdb/mmCIF/g8/6g88.cif.gz mmcif
cp /home/sness/pdb/mmCIF/g9/6g9f.cif.gz mmcif
cp /home/sness/pdb/mmCIF/g9/6g9p.cif.gz mmcif
cp /home/sness/pdb/mmCIF/g9/6g9s.cif.gz mmcif
cp /home/sness/pdb/mmCIF/g9/6g9t.cif.gz mmcif
cp /home/sness/pdb/mmCIF/go/6goa.cif.gz mmcif
cp /home/sness/pdb/mmCIF/gt/6gth.cif.gz mmcif
cp /home/sness/pdb/mmCIF/h2/6h27.cif.gz mmcif
cp /home/sness/pdb/mmCIF/h2/6h28.cif.gz mmcif
cp /home/sness/pdb/mmCIF/h2/6h2a.cif.gz mmcif
cp /home/sness/pdb/mmCIF/h2/6h2c.cif.gz mmcif
cp /home/sness/pdb/mmCIF/h2/6h2g.cif.gz mmcif
cp /home/sness/pdb/mmCIF/h2/6h2h.cif.gz mmcif
cp /home/sness/pdb/mmCIF/h2/6h2i.cif.gz mmcif
cp /home/sness/pdb/mmCIF/h2/6h2k.cif.gz mmcif
cp /home/sness/pdb/mmCIF/h5/6h5o.cif.gz mmcif
cp /home/sness/pdb/mmCIF/hb/6hb8.cif.gz mmcif
cp /home/sness/pdb/mmCIF/ho/6hoo.cif.gz mmcif
cp /home/sness/pdb/mmCIF/hr/6hr4.cif.gz mmcif
cp /home/sness/pdb/mmCIF/hr/6hr6.cif.gz mmcif
cp /home/sness/pdb/mmCIF/hr/6hr9.cif.gz mmcif
cp /home/sness/pdb/mmCIF/hz/6hzh.cif.gz mmcif
cp /home/sness/pdb/mmCIF/hz/6hzi.cif.gz mmcif
cp /home/sness/pdb/mmCIF/hz/6hzj.cif.gz mmcif
cp /home/sness/pdb/mmCIF/hz/6hzo.cif.gz mmcif
cp /home/sness/pdb/mmCIF/hz/6hzq.cif.gz mmcif
cp /home/sness/pdb/mmCIF/hz/6hzr.cif.gz mmcif
cp /home/sness/pdb/mmCIF/i1/6i1e.cif.gz mmcif
cp /home/sness/pdb/mmCIF/i1/6i1f.cif.gz mmcif
cp /home/sness/pdb/mmCIF/i1/6i1g.cif.gz mmcif
cp /home/sness/pdb/mmCIF/i1/6i1h.cif.gz mmcif
cp /home/sness/pdb/mmCIF/i1/6i1i.cif.gz mmcif
cp /home/sness/pdb/mmCIF/i3/6i30.cif.gz mmcif
cp /home/sness/pdb/mmCIF/i5/6i5d.cif.gz mmcif
cp /home/sness/pdb/mmCIF/iq/6iqk.cif.gz mmcif
cp /home/sness/pdb/mmCIF/it/6ity.cif.gz mmcif
cp /home/sness/pdb/mmCIF/iz/6izc.cif.gz mmcif
cp /home/sness/pdb/mmCIF/iz/6izd.cif.gz mmcif
cp /home/sness/pdb/mmCIF/iz/6izw.cif.gz mmcif
cp /home/sness/pdb/mmCIF/j2/6j25.cif.gz mmcif
cp /home/sness/pdb/mmCIF/j2/6j2b.cif.gz mmcif
cp /home/sness/pdb/mmCIF/j2/6j2k.cif.gz mmcif
cp /home/sness/pdb/mmCIF/j2/6j2o.cif.gz mmcif
cp /home/sness/pdb/mmCIF/j8/6j8q.cif.gz mmcif
cp /home/sness/pdb/mmCIF/jn/6jn3.cif.gz mmcif
cp /home/sness/pdb/mmCIF/jn/6jn4.cif.gz mmcif
cp /home/sness/pdb/mmCIF/jn/6jn5.cif.gz mmcif
cp /home/sness/pdb/mmCIF/jw/6jwp.cif.gz mmcif
cp /home/sness/pdb/mmCIF/k8/6k8x.cif.gz mmcif
cp /home/sness/pdb/mmCIF/k9/6k9t.cif.gz mmcif
cp /home/sness/pdb/mmCIF/ka/6ka5.cif.gz mmcif
cp /home/sness/pdb/mmCIF/kb/6kby.cif.gz mmcif
cp /home/sness/pdb/mmCIF/kg/6kgh.cif.gz mmcif
cp /home/sness/pdb/mmCIF/kg/6kgs.cif.gz mmcif
cp /home/sness/pdb/mmCIF/kg/6kgt.cif.gz mmcif
cp /home/sness/pdb/mmCIF/kg/6kgu.cif.gz mmcif
cp /home/sness/pdb/mmCIF/kg/6kgv.cif.gz mmcif
cp /home/sness/pdb/mmCIF/kg/6kgw.cif.gz mmcif
cp /home/sness/pdb/mmCIF/kj/6kjc.cif.gz mmcif
cp /home/sness/pdb/mmCIF/kj/6kjd.cif.gz mmcif
cp /home/sness/pdb/mmCIF/kj/6kje.cif.gz mmcif
cp /home/sness/pdb/mmCIF/kj/6kjf.cif.gz mmcif
cp /home/sness/pdb/mmCIF/kj/6kjh.cif.gz mmcif
cp /home/sness/pdb/mmCIF/kj/6kjj.cif.gz mmcif
cp /home/sness/pdb/mmCIF/kj/6kjp.cif.gz mmcif
cp /home/sness/pdb/mmCIF/kj/6kjq.cif.gz mmcif
cp /home/sness/pdb/mmCIF/kj/6kjr.cif.gz mmcif
cp /home/sness/pdb/mmCIF/kj/6kjt.cif.gz mmcif
cp /home/sness/pdb/mmCIF/ks/6ksu.cif.gz mmcif
cp /home/sness/pdb/mmCIF/ks/6ksv.cif.gz mmcif
cp /home/sness/pdb/mmCIF/lc/6lc7.cif.gz mmcif
cp /home/sness/pdb/mmCIF/lc/6lc8.cif.gz mmcif
cp /home/sness/pdb/mmCIF/lc/6lc9.cif.gz mmcif
cp /home/sness/pdb/mmCIF/lo/6lox.cif.gz mmcif
cp /home/sness/pdb/mmCIF/m5/6m5h.cif.gz mmcif
cp /home/sness/pdb/mmCIF/m5/6m5p.cif.gz mmcif
cp /home/sness/pdb/mmCIF/m5/6m5q.cif.gz mmcif
cp /home/sness/pdb/mmCIF/m7/6m7i.cif.gz mmcif
cp /home/sness/pdb/mmCIF/md/6md8.cif.gz mmcif
cp /home/sness/pdb/mmCIF/me/6mey.cif.gz mmcif
cp /home/sness/pdb/mmCIF/mg/6mgh.cif.gz mmcif
cp /home/sness/pdb/mmCIF/mi/6mia.cif.gz mmcif
cp /home/sness/pdb/mmCIF/mk/6mk6.cif.gz mmcif
cp /home/sness/pdb/mmCIF/mk/6mka.cif.gz mmcif
cp /home/sness/pdb/mmCIF/mk/6mkf.cif.gz mmcif
cp /home/sness/pdb/mmCIF/mk/6mkg.cif.gz mmcif
cp /home/sness/pdb/mmCIF/mk/6mkh.cif.gz mmcif
cp /home/sness/pdb/mmCIF/mk/6mki.cif.gz mmcif
cp /home/sness/pdb/mmCIF/mk/6mkj.cif.gz mmcif
cp /home/sness/pdb/mmCIF/mk/6mkq.cif.gz mmcif
cp /home/sness/pdb/mmCIF/ml/6mll.cif.gz mmcif
cp /home/sness/pdb/mmCIF/mn/6mnp.cif.gz mmcif
cp /home/sness/pdb/mmCIF/mp/6mpq.cif.gz mmcif
cp /home/sness/pdb/mmCIF/mu/6mu9.cif.gz mmcif
cp /home/sness/pdb/mmCIF/mu/6muq.cif.gz mmcif
cp /home/sness/pdb/mmCIF/mz/6mz1.cif.gz mmcif
cp /home/sness/pdb/mmCIF/mz/6mz2.cif.gz mmcif
cp /home/sness/pdb/mmCIF/n1/6n14.cif.gz mmcif
cp /home/sness/pdb/mmCIF/n1/6n1n.cif.gz mmcif
cp /home/sness/pdb/mmCIF/n6/6n6w.cif.gz mmcif
cp /home/sness/pdb/mmCIF/n6/6n6x.cif.gz mmcif
cp /home/sness/pdb/mmCIF/n6/6n6y.cif.gz mmcif
cp /home/sness/pdb/mmCIF/n9/6n9k.cif.gz mmcif
cp /home/sness/pdb/mmCIF/nf/6nfd.cif.gz mmcif
cp /home/sness/pdb/mmCIF/nh/6nhs.cif.gz mmcif
cp /home/sness/pdb/mmCIF/ni/6ni1.cif.gz mmcif
cp /home/sness/pdb/mmCIF/ni/6niq.cif.gz mmcif
cp /home/sness/pdb/mmCIF/nj/6nj1.cif.gz mmcif
cp /home/sness/pdb/mmCIF/nj/6njk.cif.gz mmcif
cp /home/sness/pdb/mmCIF/nl/6nlw.cif.gz mmcif
cp /home/sness/pdb/mmCIF/nt/6ntz.cif.gz mmcif
cp /home/sness/pdb/mmCIF/nv/6nvt.cif.gz mmcif
cp /home/sness/pdb/mmCIF/nv/6nvu.cif.gz mmcif
cp /home/sness/pdb/mmCIF/nz/6nz8.cif.gz mmcif
cp /home/sness/pdb/mmCIF/o9/6o9s.cif.gz mmcif
cp /home/sness/pdb/mmCIF/o9/6o9w.cif.gz mmcif
cp /home/sness/pdb/mmCIF/oa/6oap.cif.gz mmcif
cp /home/sness/pdb/mmCIF/oo/6ooe.cif.gz mmcif
cp /home/sness/pdb/mmCIF/oo/6oof.cif.gz mmcif
cp /home/sness/pdb/mmCIF/oo/6ooh.cif.gz mmcif
cp /home/sness/pdb/mmCIF/oo/6ooj.cif.gz mmcif
cp /home/sness/pdb/mmCIF/oo/6ook.cif.gz mmcif
cp /home/sness/pdb/mmCIF/os/6osu.cif.gz mmcif
cp /home/sness/pdb/mmCIF/p5/6p52.cif.gz mmcif
cp /home/sness/pdb/mmCIF/p5/6p53.cif.gz mmcif
cp /home/sness/pdb/mmCIF/p5/6p54.cif.gz mmcif
cp /home/sness/pdb/mmCIF/p5/6p55.cif.gz mmcif
cp /home/sness/pdb/mmCIF/p5/6p56.cif.gz mmcif
cp /home/sness/pdb/mmCIF/p9/6p96.cif.gz mmcif
cp /home/sness/pdb/mmCIF/p9/6p97.cif.gz mmcif
cp /home/sness/pdb/mmCIF/p9/6p98.cif.gz mmcif
cp /home/sness/pdb/mmCIF/p9/6p99.cif.gz mmcif
cp /home/sness/pdb/mmCIF/p9/6p9c.cif.gz mmcif
cp /home/sness/pdb/mmCIF/pk/6pk0.cif.gz mmcif
cp /home/sness/pdb/mmCIF/pl/6pl5.cif.gz mmcif
cp /home/sness/pdb/mmCIF/pl/6pl6.cif.gz mmcif
cp /home/sness/pdb/mmCIF/pq/6pq8.cif.gz mmcif
cp /home/sness/pdb/mmCIF/pq/6pq9.cif.gz mmcif
cp /home/sness/pdb/mmCIF/pq/6pqc.cif.gz mmcif
cp /home/sness/pdb/mmCIF/pq/6pqi.cif.gz mmcif
cp /home/sness/pdb/mmCIF/ps/6psg.cif.gz mmcif
cp /home/sness/pdb/mmCIF/ps/6psk.cif.gz mmcif
cp /home/sness/pdb/mmCIF/pt/6pt1.cif.gz mmcif
cp /home/sness/pdb/mmCIF/pt/6pt5.cif.gz mmcif
cp /home/sness/pdb/mmCIF/pt/6ptu.cif.gz mmcif
cp /home/sness/pdb/mmCIF/pw/6pwl.cif.gz mmcif
cp /home/sness/pdb/mmCIF/pw/6pwm.cif.gz mmcif
cp /home/sness/pdb/mmCIF/px/6px4.cif.gz mmcif
cp /home/sness/pdb/mmCIF/px/6pxe.cif.gz mmcif
cp /home/sness/pdb/mmCIF/px/6pxx.cif.gz mmcif
cp /home/sness/pdb/mmCIF/q3/6q35.cif.gz mmcif
cp /home/sness/pdb/mmCIF/q5/6q5b.cif.gz mmcif
cp /home/sness/pdb/mmCIF/q5/6q5f.cif.gz mmcif
cp /home/sness/pdb/mmCIF/q9/6q9n.cif.gz mmcif
cp /home/sness/pdb/mmCIF/qw/6qw7.cif.gz mmcif
cp /home/sness/pdb/mmCIF/qw/6qw8.cif.gz mmcif
cp /home/sness/pdb/mmCIF/qw/6qw9.cif.gz mmcif
cp /home/sness/pdb/mmCIF/qw/6qwa.cif.gz mmcif
cp /home/sness/pdb/mmCIF/qw/6qwb.cif.gz mmcif
cp /home/sness/pdb/mmCIF/qw/6qwc.cif.gz mmcif
cp /home/sness/pdb/mmCIF/qw/6qwd.cif.gz mmcif
cp /home/sness/pdb/mmCIF/qw/6qwe.cif.gz mmcif
cp /home/sness/pdb/mmCIF/r3/6r3x.cif.gz mmcif
cp /home/sness/pdb/mmCIF/r4/6r40.cif.gz mmcif
cp /home/sness/pdb/mmCIF/r4/6r42.cif.gz mmcif
cp /home/sness/pdb/mmCIF/rj/6rj7.cif.gz mmcif
cp /home/sness/pdb/mmCIF/rt/6rtn.cif.gz mmcif
cp /home/sness/pdb/mmCIF/s1/6s1s.cif.gz mmcif
cp /home/sness/pdb/mmCIF/sk/6skp.cif.gz mmcif
cp /home/sness/pdb/mmCIF/sk/6skq.cif.gz mmcif
cp /home/sness/pdb/mmCIF/sk/6skr.cif.gz mmcif
cp /home/sness/pdb/mmCIF/sp/6sp6.cif.gz mmcif
cp /home/sness/pdb/mmCIF/sy/6syn.cif.gz mmcif
cp /home/sness/pdb/mmCIF/t1/6t1h.cif.gz mmcif
cp /home/sness/pdb/mmCIF/t3/6t35.cif.gz mmcif
cp /home/sness/pdb/mmCIF/t3/6t3d.cif.gz mmcif
cp /home/sness/pdb/mmCIF/t5/6t5y.cif.gz mmcif
cp /home/sness/pdb/mmCIF/t7/6t7l.cif.gz mmcif
cp /home/sness/pdb/mmCIF/tb/6tbw.cif.gz mmcif
cp /home/sness/pdb/mmCIF/td/6td0.cif.gz mmcif
cp /home/sness/pdb/mmCIF/td/6td1.cif.gz mmcif
cp /home/sness/pdb/mmCIF/tp/6tpm.cif.gz mmcif
cp /home/sness/pdb/mmCIF/ts/6ts9.cif.gz mmcif
cp /home/sness/pdb/mmCIF/tw/6tww.cif.gz mmcif
cp /home/sness/pdb/mmCIF/tx/6txd.cif.gz mmcif
cp /home/sness/pdb/mmCIF/ty/6ty6.cif.gz mmcif
cp /home/sness/pdb/mmCIF/tz/6tzf.cif.gz mmcif
cp /home/sness/pdb/mmCIF/tz/6tzg.cif.gz mmcif
cp /home/sness/pdb/mmCIF/tz/6tzh.cif.gz mmcif
cp /home/sness/pdb/mmCIF/tz/6tzi.cif.gz mmcif
cp /home/sness/pdb/mmCIF/tz/6tzj.cif.gz mmcif
cp /home/sness/pdb/mmCIF/u5/6u58.cif.gz mmcif
cp /home/sness/pdb/mmCIF/ue/6ue2.cif.gz mmcif
cp /home/sness/pdb/mmCIF/uj/6ujg.cif.gz mmcif
cp /home/sness/pdb/mmCIF/uj/6ujm.cif.gz mmcif
cp /home/sness/pdb/mmCIF/uk/6uk6.cif.gz mmcif
cp /home/sness/pdb/mmCIF/uk/6ukb.cif.gz mmcif
cp /home/sness/pdb/mmCIF/ul/6ul9.cif.gz mmcif
cp /home/sness/pdb/mmCIF/ul/6ula.cif.gz mmcif
cp /home/sness/pdb/mmCIF/ul/6ulg.cif.gz mmcif
cp /home/sness/pdb/mmCIF/ul/6ulj.cif.gz mmcif
cp /home/sness/pdb/mmCIF/um/6umc.cif.gz mmcif
cp /home/sness/pdb/mmCIF/um/6umd.cif.gz mmcif
cp /home/sness/pdb/mmCIF/um/6ume.cif.gz mmcif
cp /home/sness/pdb/mmCIF/um/6umf.cif.gz mmcif
cp /home/sness/pdb/mmCIF/un/6un1.cif.gz mmcif
cp /home/sness/pdb/mmCIF/un/6un3.cif.gz mmcif
cp /home/sness/pdb/mmCIF/un/6unb.cif.gz mmcif
cp /home/sness/pdb/mmCIF/uq/6uqs.cif.gz mmcif
cp /home/sness/pdb/mmCIF/uq/6uqt.cif.gz mmcif
cp /home/sness/pdb/mmCIF/uq/6uqu.cif.gz mmcif
cp /home/sness/pdb/mmCIF/ur/6ur3.cif.gz mmcif
cp /home/sness/pdb/mmCIF/uv/6uvk.cif.gz mmcif
cp /home/sness/pdb/mmCIF/v1/6v1j.cif.gz mmcif
cp /home/sness/pdb/mmCIF/v1/6v1o.cif.gz mmcif
cp /home/sness/pdb/mmCIF/v4/6v4w.cif.gz mmcif
cp /home/sness/pdb/mmCIF/v5/6v5e.cif.gz mmcif
cp /home/sness/pdb/mmCIF/v6/6v6g.cif.gz mmcif
cp /home/sness/pdb/mmCIF/v6/6v6p.cif.gz mmcif
cp /home/sness/pdb/mmCIF/v7/6v7h.cif.gz mmcif
cp /home/sness/pdb/mmCIF/v7/6v7i.cif.gz mmcif
cp /home/sness/pdb/mmCIF/v7/6v7t.cif.gz mmcif
cp /home/sness/pdb/mmCIF/v8/6v83.cif.gz mmcif
cp /home/sness/pdb/mmCIF/v8/6v8v.cif.gz mmcif
cp /home/sness/pdb/mmCIF/vb/6vbc.cif.gz mmcif
cp /home/sness/pdb/mmCIF/vb/6vbd.cif.gz mmcif
cp /home/sness/pdb/mmCIF/vb/6vbl.cif.gz mmcif
cp /home/sness/pdb/mmCIF/vb/6vbm.cif.gz mmcif
cp /home/sness/pdb/mmCIF/vh/6vhs.cif.gz mmcif
cp /home/sness/pdb/mmCIF/vj/6vje.cif.gz mmcif
cp /home/sness/pdb/mmCIF/vn/6vnu.cif.gz mmcif
cp /home/sness/pdb/mmCIF/vo/6vot.cif.gz mmcif
cp /home/sness/pdb/mmCIF/w2/6w2z.cif.gz mmcif
cp /home/sness/pdb/mmCIF/w3/6w33.cif.gz mmcif
cp /home/sness/pdb/mmCIF/w3/6w34.cif.gz mmcif
cp /home/sness/pdb/mmCIF/w5/6w5e.cif.gz mmcif
cp /home/sness/pdb/mmCIF/w5/6w5f.cif.gz mmcif
cp /home/sness/pdb/mmCIF/w5/6w5g.cif.gz mmcif
cp /home/sness/pdb/mmCIF/w5/6w5o.cif.gz mmcif
cp /home/sness/pdb/mmCIF/wa/6wa7.cif.gz mmcif
cp /home/sness/pdb/mmCIF/wg/6wgp.cif.gz mmcif
cp /home/sness/pdb/mmCIF/wg/6wgq.cif.gz mmcif
cp /home/sness/pdb/mmCIF/wg/6wgr.cif.gz mmcif
cp /home/sness/pdb/mmCIF/wh/6whf.cif.gz mmcif
cp /home/sness/pdb/mmCIF/wi/6wif.cif.gz mmcif
cp /home/sness/pdb/mmCIF/wi/6wip.cif.gz mmcif
cp /home/sness/pdb/mmCIF/wj/6wjm.cif.gz mmcif
cp /home/sness/pdb/mmCIF/wy/6wy4.cif.gz mmcif
cp /home/sness/pdb/mmCIF/x9/6x9y.cif.gz mmcif
cp /home/sness/pdb/mmCIF/xd/6xd5.cif.gz mmcif
cp /home/sness/pdb/mmCIF/xd/6xd7.cif.gz mmcif
cp /home/sness/pdb/mmCIF/xf/6xfs.cif.gz mmcif
cp /home/sness/pdb/mmCIF/xg/6xg1.cif.gz mmcif
cp /home/sness/pdb/mmCIF/xj/6xj3.cif.gz mmcif
cp /home/sness/pdb/mmCIF/xj/6xj8.cif.gz mmcif
cp /home/sness/pdb/mmCIF/xq/6xqr.cif.gz mmcif
cp /home/sness/pdb/mmCIF/xq/6xqv.cif.gz mmcif
cp /home/sness/pdb/mmCIF/xq/6xqx.cif.gz mmcif
cp /home/sness/pdb/mmCIF/xq/6xqy.cif.gz mmcif
cp /home/sness/pdb/mmCIF/xq/6xqz.cif.gz mmcif
cp /home/sness/pdb/mmCIF/y6/6y6u.cif.gz mmcif
cp /home/sness/pdb/mmCIF/y6/6y6z.cif.gz mmcif
cp /home/sness/pdb/mmCIF/ye/6yen.cif.gz mmcif
cp /home/sness/pdb/mmCIF/ye/6yeo.cif.gz mmcif
cp /home/sness/pdb/mmCIF/yn/6yn0.cif.gz mmcif
cp /home/sness/pdb/mmCIF/yp/6ypd.cif.gz mmcif
cp /home/sness/pdb/mmCIF/yr/6yra.cif.gz mmcif
cp /home/sness/pdb/mmCIF/yr/6yrs.cif.gz mmcif
cp /home/sness/pdb/mmCIF/z2/6z21.cif.gz mmcif
cp /home/sness/pdb/mmCIF/z2/6z22.cif.gz mmcif
cp /home/sness/pdb/mmCIF/z2/6z23.cif.gz mmcif
cp /home/sness/pdb/mmCIF/z2/6z24.cif.gz mmcif
cp /home/sness/pdb/mmCIF/z2/6z25.cif.gz mmcif
cp /home/sness/pdb/mmCIF/z7/6z7h.cif.gz mmcif
cp /home/sness/pdb/mmCIF/z7/6z7i.cif.gz mmcif
cp /home/sness/pdb/mmCIF/z7/6z7j.cif.gz mmcif
cp /home/sness/pdb/mmCIF/z7/6z7k.cif.gz mmcif
cp /home/sness/pdb/mmCIF/zr/6zrg.cif.gz mmcif
cp /home/sness/pdb/mmCIF/zr/6zrh.cif.gz mmcif
cp /home/sness/pdb/mmCIF/zr/6zri.cif.gz mmcif
cp /home/sness/pdb/mmCIF/zr/6zrj.cif.gz mmcif
cp /home/sness/pdb/mmCIF/zr/6zrp.cif.gz mmcif
cp /home/sness/pdb/mmCIF/zw/6zw2.cif.gz mmcif
cp /home/sness/pdb/mmCIF/zx/6zxi.cif.gz mmcif
cp /home/sness/pdb/mmCIF/a5/7a5t.cif.gz mmcif
cp /home/sness/pdb/mmCIF/a5/7a5u.cif.gz mmcif
cp /home/sness/pdb/mmCIF/a5/7a5w.cif.gz mmcif
cp /home/sness/pdb/mmCIF/a6/7a61.cif.gz mmcif
cp /home/sness/pdb/mmCIF/a6/7a6z.cif.gz mmcif
cp /home/sness/pdb/mmCIF/a7/7a71.cif.gz mmcif
cp /home/sness/pdb/mmCIF/a7/7a72.cif.gz mmcif
cp /home/sness/pdb/mmCIF/a7/7a74.cif.gz mmcif
cp /home/sness/pdb/mmCIF/as/7ass.cif.gz mmcif
cp /home/sness/pdb/mmCIF/at/7ato.cif.gz mmcif
cp /home/sness/pdb/mmCIF/at/7atw.cif.gz mmcif
cp /home/sness/pdb/mmCIF/at/7atx.cif.gz mmcif
cp /home/sness/pdb/mmCIF/au/7au0.cif.gz mmcif
cp /home/sness/pdb/mmCIF/au/7au1.cif.gz mmcif
cp /home/sness/pdb/mmCIF/au/7au8.cif.gz mmcif
cp /home/sness/pdb/mmCIF/au/7au9.cif.gz mmcif
cp /home/sness/pdb/mmCIF/au/7aub.cif.gz mmcif
cp /home/sness/pdb/mmCIF/au/7auh.cif.gz mmcif
cp /home/sness/pdb/mmCIF/au/7aux.cif.gz mmcif
cp /home/sness/pdb/mmCIF/aw/7aw5.cif.gz mmcif
cp /home/sness/pdb/mmCIF/b3/7b3r.cif.gz mmcif
cp /home/sness/pdb/mmCIF/b3/7b3s.cif.gz mmcif
cp /home/sness/pdb/mmCIF/b3/7b3u.cif.gz mmcif
cp /home/sness/pdb/mmCIF/bd/7bdr.cif.gz mmcif
cp /home/sness/pdb/mmCIF/bd/7bds.cif.gz mmcif
cp /home/sness/pdb/mmCIF/bh/7bh3.cif.gz mmcif
cp /home/sness/pdb/mmCIF/bh/7bh4.cif.gz mmcif
cp /home/sness/pdb/mmCIF/bh/7bh5.cif.gz mmcif
cp /home/sness/pdb/mmCIF/bh/7bh6.cif.gz mmcif
cp /home/sness/pdb/mmCIF/bh/7bh7.cif.gz mmcif
cp /home/sness/pdb/mmCIF/bn/7bn9.cif.gz mmcif
cp /home/sness/pdb/mmCIF/ci/7cin.cif.gz mmcif
cp /home/sness/pdb/mmCIF/ct/7ct3.cif.gz mmcif
cp /home/sness/pdb/mmCIF/cy/7cy1.cif.gz mmcif
cp /home/sness/pdb/mmCIF/d5/7d5j.cif.gz mmcif
cp /home/sness/pdb/mmCIF/dd/7ddm.cif.gz mmcif
cp /home/sness/pdb/mmCIF/dm/7dml.cif.gz mmcif
cp /home/sness/pdb/mmCIF/do/7doo.cif.gz mmcif
cp /home/sness/pdb/mmCIF/e9/7e9a.cif.gz mmcif
cp /home/sness/pdb/mmCIF/jh/7jhq.cif.gz mmcif
cp /home/sness/pdb/mmCIF/jw/7jwl.cif.gz mmcif
cp /home/sness/pdb/mmCIF/k2/7k2w.cif.gz mmcif
cp /home/sness/pdb/mmCIF/k2/7k2x.cif.gz mmcif
cp /home/sness/pdb/mmCIF/k2/7k2y.cif.gz mmcif
cp /home/sness/pdb/mmCIF/k3/7k3m.cif.gz mmcif
cp /home/sness/pdb/mmCIF/k5/7k5v.cif.gz mmcif
cp /home/sness/pdb/mmCIF/k8/7k8e.cif.gz mmcif
cp /home/sness/pdb/mmCIF/k8/7k8f.cif.gz mmcif
cp /home/sness/pdb/mmCIF/k8/7k8h.cif.gz mmcif
cp /home/sness/pdb/mmCIF/k8/7k8k.cif.gz mmcif
cp /home/sness/pdb/mmCIF/k8/7k8l.cif.gz mmcif
cp /home/sness/pdb/mmCIF/kc/7kcv.cif.gz mmcif
cp /home/sness/pdb/mmCIF/kc/7kcw.cif.gz mmcif
cp /home/sness/pdb/mmCIF/kc/7kcx.cif.gz mmcif
cp /home/sness/pdb/mmCIF/kc/7kcy.cif.gz mmcif
cp /home/sness/pdb/mmCIF/ke/7kep.cif.gz mmcif
cp /home/sness/pdb/mmCIF/ke/7keq.cif.gz mmcif
cp /home/sness/pdb/mmCIF/ke/7ker.cif.gz mmcif
cp /home/sness/pdb/mmCIF/kh/7kh9.cif.gz mmcif
cp /home/sness/pdb/mmCIF/kh/7khq.cif.gz mmcif
cp /home/sness/pdb/mmCIF/kh/7khy.cif.gz mmcif
cp /home/sness/pdb/mmCIF/kh/7khz.cif.gz mmcif
cp /home/sness/pdb/mmCIF/ki/7kis.cif.gz mmcif
cp /home/sness/pdb/mmCIF/ki/7kit.cif.gz mmcif
cp /home/sness/pdb/mmCIF/ki/7kiv.cif.gz mmcif
cp /home/sness/pdb/mmCIF/ki/7kiw.cif.gz mmcif
cp /home/sness/pdb/mmCIF/l5/7l5r.cif.gz mmcif
cp /home/sness/pdb/mmCIF/l5/7l5t.cif.gz mmcif
cp /home/sness/pdb/mmCIF/l5/7l5v.cif.gz mmcif
cp /home/sness/pdb/mmCIF/l8/7l8o.cif.gz mmcif
cp /home/sness/pdb/mmCIF/lc/7lc4.cif.gz mmcif
cp /home/sness/pdb/mmCIF/lj/7ljk.cif.gz mmcif
cp /home/sness/pdb/mmCIF/lk/7lk8.cif.gz mmcif
cp /home/sness/pdb/mmCIF/ll/7llb.cif.gz mmcif
cp /home/sness/pdb/mmCIF/ll/7llh.cif.gz mmcif
cp /home/sness/pdb/mmCIF/ln/7lnl.cif.gz mmcif
cp /home/sness/pdb/mmCIF/ln/7lno.cif.gz mmcif
cp /home/sness/pdb/mmCIF/ln/7lnq.cif.gz mmcif
cp /home/sness/pdb/mmCIF/ln/7lnr.cif.gz mmcif
cp /home/sness/pdb/mmCIF/lq/7lq6.cif.gz mmcif
cp /home/sness/pdb/mmCIF/lx/7lxg.cif.gz mmcif
cp /home/sness/pdb/mmCIF/ly/7ly1.cif.gz mmcif
cp /home/sness/pdb/mmCIF/me/7me9.cif.gz mmcif
cp /home/sness/pdb/mmCIF/me/7mea.cif.gz mmcif
cp /home/sness/pdb/mmCIF/me/7meb.cif.gz mmcif
cp /home/sness/pdb/mmCIF/me/7mec.cif.gz mmcif
cp /home/sness/pdb/mmCIF/me/7med.cif.gz mmcif
cp /home/sness/pdb/mmCIF/me/7mee.cif.gz mmcif
cp /home/sness/pdb/mmCIF/me/7mef.cif.gz mmcif
cp /home/sness/pdb/mmCIF/me/7meg.cif.gz mmcif
cp /home/sness/pdb/mmCIF/me/7meh.cif.gz mmcif
cp /home/sness/pdb/mmCIF/mq/7mqn.cif.gz mmcif
cp /home/sness/pdb/mmCIF/o4/7o49.cif.gz mmcif
cp /home/sness/pdb/mmCIF/o4/7o4b.cif.gz mmcif
cp /home/sness/pdb/mmCIF/od/7oda.cif.gz mmcif
cp /home/sness/pdb/mmCIF/ok/7ok9.cif.gz mmcif
cp /home/sness/pdb/mmCIF/on/7onk.cif.gz mmcif
cp /home/sness/pdb/mmCIF/on/7onn.cif.gz mmcif
cp /home/sness/pdb/mmCIF/on/7ono.cif.gz mmcif
cp /home/sness/pdb/mmCIF/on/7onw.cif.gz mmcif
cp /home/sness/pdb/mmCIF/on/7onx.cif.gz mmcif
cp /home/sness/pdb/mmCIF/on/7ony.cif.gz mmcif
cp /home/sness/pdb/mmCIF/on/7onz.cif.gz mmcif
cp /home/sness/pdb/mmCIF/q0/7q0y.cif.gz mmcif
cp /home/sness/pdb/mmCIF/q0/7q0z.cif.gz mmcif
cp /home/sness/pdb/mmCIF/q1/7q11.cif.gz mmcif
cp /home/sness/pdb/mmCIF/q3/7q3d.cif.gz mmcif
cp /home/sness/pdb/mmCIF/qq/7qq5.cif.gz mmcif
cp /home/sness/pdb/mmCIF/qq/7qqc.cif.gz mmcif
cp /home/sness/pdb/mmCIF/r3/7r3q.cif.gz mmcif
cp /home/sness/pdb/mmCIF/r3/7r3r.cif.gz mmcif
cp /home/sness/pdb/mmCIF/r6/7r6z.cif.gz mmcif
cp /home/sness/pdb/mmCIF/rc/7rcw.cif.gz mmcif
cp /home/sness/pdb/mmCIF/rc/7rcx.cif.gz mmcif
cp /home/sness/pdb/mmCIF/rc/7rcy.cif.gz mmcif
cp /home/sness/pdb/mmCIF/rc/7rcz.cif.gz mmcif
cp /home/sness/pdb/mmCIF/rd/7rd0.cif.gz mmcif
cp /home/sness/pdb/mmCIF/re/7ren.cif.gz mmcif
cp /home/sness/pdb/mmCIF/rg/7rgg.cif.gz mmcif
cp /home/sness/pdb/mmCIF/rl/7rl8.cif.gz mmcif
cp /home/sness/pdb/mmCIF/rl/7rlr.cif.gz mmcif
cp /home/sness/pdb/mmCIF/s0/7s0v.cif.gz mmcif
cp /home/sness/pdb/mmCIF/sb/7sbm.cif.gz mmcif
cp /home/sness/pdb/mmCIF/sb/7sbn.cif.gz mmcif
cp /home/sness/pdb/mmCIF/t7/7t7d.cif.gz mmcif
cp /home/sness/pdb/mmCIF/t7/7t7e.cif.gz mmcif
cp /home/sness/pdb/mmCIF/t7/7t7f.cif.gz mmcif
cp /home/sness/pdb/mmCIF/t7/7t7g.cif.gz mmcif
cp /home/sness/pdb/mmCIF/tb/7tb7.cif.gz mmcif
cp /home/sness/pdb/mmCIF/tb/7tbx.cif.gz mmcif
cp /home/sness/pdb/mmCIF/tc/7tc1.cif.gz mmcif
cp /home/sness/pdb/mmCIF/ti/7ti0.cif.gz mmcif
cp /home/sness/pdb/mmCIF/u4/7u48.cif.gz mmcif
cp /home/sness/pdb/mmCIF/u4/7u49.cif.gz mmcif
cp /home/sness/pdb/mmCIF/u4/7u4b.cif.gz mmcif
cp /home/sness/pdb/mmCIF/u4/7u4h.cif.gz mmcif
cp /home/sness/pdb/mmCIF/u5/7u57.cif.gz mmcif
cp /home/sness/pdb/mmCIF/v1/7v1y.cif.gz mmcif
cp /home/sness/pdb/mmCIF/v1/7v1z.cif.gz mmcif
cp /home/sness/pdb/mmCIF/v2/7v21.cif.gz mmcif
