cp ~/pdb/pdb/zipped/pdb1alq.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb1axb.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb1blc.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb1blh.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb1blp.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb1bls.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb1bsg.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb1bt5.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb1btl.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb1bue.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb1bul.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb1bza.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb1c3b.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb1cef.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb1ceg.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb1ci8.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb1ci9.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb1ck3.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb1dja.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb1djb.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb1djc.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb1dy6.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb1e25.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb1e3u.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb1e4d.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb1ei5.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb1erm.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb1ero.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb1erq.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb1es2.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb1es3.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb1es4.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb1es5.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb1esi.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb1esu.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb1ewz.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb1fcm.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb1fcn.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb1fco.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb1fof.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb1fqg.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb1fr1.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb1fr6.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb1fsw.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb1fsy.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb1g5u.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb1g68.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb1g6a.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb1ga0.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb1ga9.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb1gce.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb1ghi.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb1ghm.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb1ghp.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb1h5x.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb1h8y.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb1h8z.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb1hd8.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb1hlu.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb1htz.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb1hvb.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb1hzo.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb1i2s.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb1i2w.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb1i5q.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb1iel.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb1iem.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb1ikg.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb1iki.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb1iyo.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb1iyp.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb1iyq.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb1iys.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb1j3w.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb1j9m.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb1jtd.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb1jtg.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb1jvj.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb1jwp.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb1jwv.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb1jwz.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb1k0k.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb1k25.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb1k38.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb1k4e.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb1k4f.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb1k54.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb1k55.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb1k56.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb1k57.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb1k6r.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb1k6s.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb1kds.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb1kdw.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb1ke0.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb1ke3.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb1ke4.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb1kge.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb1kgf.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb1kgg.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb1kvl.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb1kvm.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb1l0d.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb1l0e.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb1l0f.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb1l0g.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb1l2s.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb1lhy.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb1li0.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb1li9.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb1ll5.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb1ll9.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb1llb.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb1m40.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb1m6k.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb1mbl.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb1mki.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb1mpl.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb1mwr.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb1mws.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb1mwt.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb1mwu.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb1mxo.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb1my8.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb1n4o.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb1n9b.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb1nj4.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb1nrf.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb1nxy.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb1ny0.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb1nym.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb1nyy.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb1nzo.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb1nzu.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb1o07.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb1o7e.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb1ome.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb1ong.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb1onh.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb1pi4.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb1pi5.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb1pio.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb1pw1.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb1pw8.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb1pwc.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb1pwd.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb1pwg.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb1pyy.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb1pzo.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb1pzp.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb1q2p.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb1q2q.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb1qme.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb1qmf.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb1rcj.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb1rgy.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb1rgz.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb1rp5.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb1s0w.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb1s6r.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb1scw.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb1sde.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb1sdn.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb1shv.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb1skf.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb1sko.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb1stz.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb1tdg.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb1tdl.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb1tem.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb1tvf.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb1u60.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb1uyn.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb1vet.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb1vm1.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb1vqq.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb1w5d.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb1w79.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb1w7f.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb1w8q.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb1w8y.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb1we4.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb1wyb.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb1wyc.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb1xa1.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb1xa7.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb1xgi.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb1xgj.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb1xkz.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb1xp4.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb1xpb.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb1xx2.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb1xxm.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb1y54.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb1ykd.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb1ylj.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb1ylp.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb1ylt.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb1ylw.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb1yly.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb1ylz.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb1ym1.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb1yms.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb1ymx.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb1yqs.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb1yt4.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb1z6f.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb1zc2.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb1zg4.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb1zg6.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb1zkj.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb2a3u.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb2a49.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb2b5r.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb2bg1.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb2bls.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb2c5w.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb2c6w.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb2dcf.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb2dns.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb2drw.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb2e8i.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb2efu.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb2efx.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb2ex2.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb2ex6.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb2ex8.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb2ex9.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb2exa.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb2exb.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb2fff.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb2ffy.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb2g2u.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb2g2w.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb2gdn.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb2h0t.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb2h0y.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb2h10.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb2h5s.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb2hdq.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb2hdr.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb2hds.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb2hdu.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb2hf6.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb2hp5.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb2hp6.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb2hp9.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb2hpb.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb2i72.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb2iwb.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb2iwc.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb2iwd.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb2j7v.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb2j8y.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb2j9o.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb2j9p.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb2jbf.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb2jc7.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb2jch.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb2je5.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb2jkf.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb2jkg.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb2olu.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb2olv.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb2osu.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb2ov5.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb2p74.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb2p9v.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb2pby.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb2pu2.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb2pu4.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb2q9m.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb2q9n.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb2qmi.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb2qpn.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb2qyb.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb2qz6.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb2r9w.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb2r9x.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb2rcx.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb2rl3.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb2uwx.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb2v1z.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb2v20.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb2v2f.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb2vgj.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb2vgk.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb2vjw.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb2vzw.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb2w1t.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb2wad.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb2wae.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb2waf.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb2wgi.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb2wgv.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb2wgw.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb2wk0.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb2wke.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb2wkh.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb2wki.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb2wuq.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb2wyx.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb2wzx.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb2wzz.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb2x01.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb2x02.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb2x71.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb2xd1.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb2xd5.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb2xdm.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb2xep.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb2xf3.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb2xfs.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb2xft.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb2xgn.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb2xh9.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb2xk1.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb2xln.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb2xqz.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb2xr0.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb2y2g.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb2y2h.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb2y2i.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb2y2j.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb2y2k.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb2y2l.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb2y2m.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb2y2n.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb2y2o.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb2y2p.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb2y2q.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb2y59.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb2y91.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb2z2l.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb2z2m.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb2zc3.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb2zc4.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb2zc5.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb2zc6.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb2zc7.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb2zd8.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb2zj9.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb2zl1.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb2zly.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb2zm0.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb2zm2.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb2zm7.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb2zm8.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb2zm9.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb2zma.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb2zq7.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb2zq8.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb2zq9.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb2zqa.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb2zqc.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb2zqd.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb3a3d.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb3a3e.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb3a3f.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb3a3i.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb3a3j.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb3a65.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb3a66.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb3agd.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb3age.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb3agf.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb3b3x.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb3beb.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb3bec.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb3bfc.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb3bfd.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb3bfe.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb3bff.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb3bfg.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb3blm.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb3bls.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb3bm6.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb3brm.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb3byd.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb3c4o.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb3c4p.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb3c5a.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb3c7u.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb3c7v.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb3cg5.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb3cit.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb3cjm.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb3cmz.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb3czd.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb3d4f.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb3dtm.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb3dw0.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb3dwk.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb3dwz.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb3e2k.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb3e2l.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb3eea.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb3equ.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb3eqv.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb3fkv.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb3fkw.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb3fv7.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb3fwl.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb3fyz.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb3fzc.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb3g2y.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb3g2z.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb3g30.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb3g31.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb3g32.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb3g34.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb3g35.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb3g4p.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb3gmw.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb3gqz.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb3gr2.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb3grj.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb3gsg.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb3gtc.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb3gv9.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb3gvb.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb3hbr.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb3hl9.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb3hlb.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb3hlc.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb3hld.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb3hle.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb3hlf.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb3hlg.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb3hlw.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb3hre.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb3hum.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb3hun.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb3huo.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb3hvf.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb3i7j.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb3if5.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb3if6.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb3ih8.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb3ih9.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb3iha.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb3ihb.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb3iqa.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb3isg.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb3it9.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb3ita.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb3itb.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb3iwi.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb3iwo.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb3iwq.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb3ixb.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb3ixd.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb3ixg.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb3ixh.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb3jyi.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb3kye.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb3lce.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb3leq.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb3lez.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb3lo7.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb3ly3.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb3ly4.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb3m2j.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb3m2k.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb3m6b.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb3m6h.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb3mbz.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb3mfd.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb3mke.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb3mkf.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb3mxr.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb3mxs.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb3mzd.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb3mze.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb3mzf.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb3n4i.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb3n6i.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb3n7w.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb3n8l.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb3n8r.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb3n8s.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb3n91.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb3nbl.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb3nc8.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb3nck.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb3nde.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb3ndg.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb3ni9.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb3nia.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb3ny4.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb3o5y.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb3o86.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb3o87.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb3o88.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb3oc2.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb3ocl.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb3ocn.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb3oov.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb3oph.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb3opl.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb3opp.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb3opr.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb3ozh.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb3p09.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb3p98.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb3pae.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb3pag.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb3pbn.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb3pbo.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb3pbq.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb3pbr.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb3pbs.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb3pbt.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb3pte.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb3q07.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb3q1f.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb3q7v.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb3q7z.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb3q81.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb3q82.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb3qhy.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb3qnb.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb3qnc.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb3rju.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb3rxw.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb3rxx.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb3s1y.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb3s22.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb3s4x.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb3sh7.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb3sh8.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb3sh9.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb3soi.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb3ss3.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb3ss4.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb3ss5.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb3t12.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb3t1q.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb3t1r.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb3t1s.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb3t1x.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb3tg9.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb3toi.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb3trc.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb3tsg.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb3udf.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb3udi.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb3udx.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb3ue0.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb3ue1.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb3ue3.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb3un7.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb3unw.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb3uo9.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb3upn.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb3upo.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb3upp.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb3uy6.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb3v39.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb3v3r.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb3v3s.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb3v50.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb3v5m.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb3vff.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb3vfh.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb3vma.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb3voy.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb3voz.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb3vp0.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb3vp1.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb3vp2.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb3vp3.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb3vp4.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb3vsk.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb3vsl.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb3vwn.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb3w4o.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb3w4p.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb3w4q.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb3w8k.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb3wrt.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb3wrz.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb3ws0.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb3ws1.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb3ws2.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb3ws4.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb3ws5.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb3wwx.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb3zcz.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb3zdj.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb3zfz.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb3zg0.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb3zg5.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb3zg9.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb3zga.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb3zhh.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb3znt.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb3zny.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb3zvt.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb3zvw.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb3zyt.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb4a5r.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb4afi.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb4b88.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb4b93.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb4bd0.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb4bd1.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb4ben.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb4bjp.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb4bl2.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb4bl3.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb4blm.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb4bqm.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb4c3q.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb4c6y.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb4c75.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb4cjn.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb4clc.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb4cpk.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb4d2o.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb4df6.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb4dki.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb4drt.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb4dxb.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb4dxc.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb4e3i.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb4e3j.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb4e3k.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb4e3l.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb4e3m.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb4e3n.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb4e3o.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb4e6w.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb4e6x.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb4ebl.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb4ebn.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb4ebp.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb4eqi.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb4euz.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb4ev4.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb4ewf.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb4f94.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb4fcf.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb4fd8.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb4fh2.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb4fh4.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb4fsf.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb4gb7.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb4gdn.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb4gku.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb4gzb.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb4hbt.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb4hbu.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb4hef.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb4hes.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb4ibr.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb4ibx.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb4id4.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb4ied.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb4ivi.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb4ivk.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb4jbf.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb4jf4.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb4jf5.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb4jf6.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb4jlf.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb4jpm.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb4jxg.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb4jxs.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb4jxv.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb4jxw.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb4k0x.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb4k91.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb4ken.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb4kg2.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb4kg5.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb4kg6.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb4kqq.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb4kz3.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb4kz4.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb4kz5.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb4kz6.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb4kz7.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb4kz8.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb4kz9.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb4kza.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb4kzb.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb4l0l.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb4lcl.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb4lcm.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb4len.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb4lv0.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb4lv1.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb4lv2.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb4lv3.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb4m3k.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb4mbf.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb4mbh.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb4mbk.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb4mez.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb4mll.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb4mnr.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb4mx4.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb4mxb.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb4mxg.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb4mxh.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb4n1h.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb4n1x.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb4n92.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb4n9k.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb4n9l.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb4net.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb4o7d.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb4oh0.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb4okp.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb4old.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb4olg.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb4ool.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb4oom.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb4oon.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb4ooy.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb4op5.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb4op8.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb4opq.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb4opr.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb4opy.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb4opz.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb4oq0.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb4oqg.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb4oqh.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb4oqi.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb4ovd.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb4p0m.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb4p6b.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb4p85.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb4p87.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb4pm5.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb4pm6.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb4pm7.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb4pm8.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb4pm9.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb4pma.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb4ppr.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb4q8i.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb4qb8.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb4qd4.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb4qhc.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb4qjg.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb4qu3.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb4qwo.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb4qy5.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb4qy6.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb4r0q.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb4r1g.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb4r23.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb4r3b.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb4r3j.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb4r4r.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb4r4s.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb4ra7.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb4rva.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb4rx2.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb4rx3.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb4rye.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb4s2i.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb4s2j.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb4s2k.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb4s2l.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb4s2m.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb4s2n.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb4s2o.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb4s2p.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb4u0t.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb4u0x.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb4u3t.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb4ua6.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb4ua7.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb4ua9.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb4uaa.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb4uhu.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb4wbg.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb4wej.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb4wek.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb4wel.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb4wm9.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb4wmc.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb4wyy.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb4wz4.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb4wz5.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb4x53.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb4x55.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb4x56.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb4x68.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb4x69.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb4x6t.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb4xux.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb4xuz.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb4xxr.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb4y0o.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb4y0t.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb4y0u.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb4y7p.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb4ye5.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb4yfm.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb4yin.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb4z9q.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb4zam.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb4zbe.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb4zdx.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb4zj1.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb4zj2.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb4zj3.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb4ztk.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb5a90.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb5a91.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb5a92.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb5a93.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb5aq7.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb5aq8.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb5aq9.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb5aqa.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb5aqb.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb5boh.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb5ceb.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb5cec.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb5ced.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb5cer.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb5cgs.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb5cgw.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb5cgx.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb5chj.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb5chm.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb5chu.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb5crf.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb5ctm.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb5ctn.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb5cxw.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb5d3o.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb5df7.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb5df8.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb5df9.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb5dfx.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb5dtk.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb5dts.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb5dtt.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb5dva.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb5dvy.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb5e2e.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb5e2f.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb5e2g.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb5e2h.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb5e31.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb5e43.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb5ee8.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb5eec.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb5eoe.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb5eoo.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb5eph.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb5eua.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb5evi.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb5evl.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb5f1f.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb5f1g.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb5f82.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb5f83.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb5fa7.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb5fao.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb5fap.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb5faq.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb5fas.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb5fat.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb5fdh.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb5fgz.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb5fi2.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb5fi6.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb5fi7.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb5fq9.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb5fqi.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb5fqj.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb5fqk.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb5fqm.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb5fqq.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb5fsr.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb5g18.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb5ggw.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb5ghx.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb5ghy.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb5ghz.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb5gkv.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb5gl9.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb5gla.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb5glb.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb5glc.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb5gld.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb5gmx.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb5gs8.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb5gsc.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb5gwa.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb5gzw.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb5hai.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb5hap.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb5haq.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb5har.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb5hfo.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb5hl1.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb5hl9.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb5hla.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb5hlb.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb5hld.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb5hvi.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb5hw1.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb5hw3.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb5hw5.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb5hx9.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb5hzi.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb5i52.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb5i63.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb5i94.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb5ihv.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb5iq8.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb5iy2.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb5j8x.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb5joc.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb5jyo.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb5jyp.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb5k1d.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb5k1f.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb5kkf.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb5kmt.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb5kmu.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb5kmw.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb5kpu.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb5ksc.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb5ksh.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb5kzh.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb5l07.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb5l09.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb5l2f.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb5ldd.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb5ll7.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb5llw.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb5loe.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb5lp4.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb5lp5.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb5lwf.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb5m18.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb5m19.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb5m1a.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb5m45.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb5mgi.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb5mmj.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb5mmy.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb5mnu.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb5mox.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb5moz.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb5n0l.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb5ne1.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb5ne2.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb5ne3.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb5nj2.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb5npo.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb5nvs.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb5nw4.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb5odz.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb5oe0.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb5oe2.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb5oft.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb5oj0.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb5oyo.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb5qa4.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb5qa5.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb5qa6.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb5qa7.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb5qa8.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb5qa9.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb5qaa.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb5qab.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb5qac.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb5qad.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb5qae.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb5qaf.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb5qag.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb5qah.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb5qai.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb5qaj.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb5qak.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb5qal.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb5qam.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb5qan.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb5qao.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb5qap.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb5qaq.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb5qar.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb5qas.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb5qat.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb5qau.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb5qav.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb5qaw.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb5qax.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb5qay.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb5qaz.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb5qb0.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb5qb1.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb5qb2.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb5qb3.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb5qb4.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb5svc.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb5t66.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb5tfq.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb5tg4.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb5tg5.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb5tg6.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb5tg7.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb5tgf.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb5tjj.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb5top.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb5toy.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb5tr7.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb5tro.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb5tw4.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb5tw6.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb5tw8.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb5twd.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb5twe.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb5tx9.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb5txi.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb5ty2.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb5ty7.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb5u2g.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb5u47.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb5u53.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb5uj3.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb5uj4.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb5ujo.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb5ul8.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb5uqe.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb5uy7.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb5vfd.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb5vle.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb5vpq.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb5vth.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb5w12.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb5w13.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb5w14.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb5w2j.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb5wac.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb5wad.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb5wae.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb5waf.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb5wag.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb5whm.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb5wi3.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb5wi7.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb5wib.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb5wj6.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb5x5g.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb5x6u.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb5xhr.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb5za2.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb5zb7.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb5zfl.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb5zft.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb5zg6.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb5zh8.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb5zqa.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb5zqb.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb5zqc.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb5zqd.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb5zqe.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb5zwq.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb5zwr.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb5zwv.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb5zyb.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb5zzb.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb6afm.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb6afn.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb6afo.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb6afp.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb6apa.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb6ayk.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb6azi.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb6b1f.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb6b1h.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb6b1j.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb6b1w.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb6b1x.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb6b1y.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb6b22.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb6b2n.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb6b5x.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb6b5y.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb6b68.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb6b69.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb6b6a.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb6b6b.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb6b6c.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb6b6d.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb6b6e.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb6b6f.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb6b9x.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb6bn3.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb6bpf.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb6bsq.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb6bsr.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb6bt6.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb6bu3.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb6c39.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb6c3k.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb6c78.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb6c79.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb6c7a.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb6c84.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb6ces.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb6cyk.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb6cyn.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb6cyq.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb6cyu.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb6d15.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb6d16.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb6d17.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb6d18.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb6d19.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb6d3g.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb6d7h.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb6d7i.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb6dgu.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb6dmh.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb6dpt.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb6dpx.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb6dpy.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb6dpz.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb6dz8.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb6edm.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb6ehp.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb6ehr.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb6fm6.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb6ftd.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb6g0k.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb6g88.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb6g9f.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb6g9p.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb6g9s.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb6g9t.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb6goa.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb6gth.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb6h27.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb6h28.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb6h2a.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb6h2c.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb6h2g.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb6h2h.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb6h2i.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb6h2k.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb6h5o.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb6hb8.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb6hoo.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb6hr4.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb6hr6.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb6hr9.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb6hzh.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb6hzi.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb6hzj.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb6hzo.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb6hzq.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb6hzr.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb6i1e.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb6i1f.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb6i1g.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb6i1h.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb6i1i.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb6i30.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb6i5d.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb6iqk.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb6ity.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb6izc.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb6izd.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb6izw.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb6j25.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb6j2b.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb6j2k.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb6j2o.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb6j8q.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb6jn3.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb6jn4.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb6jn5.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb6jwp.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb6k8x.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb6k9t.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb6ka5.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb6kby.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb6kgh.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb6kgs.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb6kgt.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb6kgu.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb6kgv.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb6kgw.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb6kjc.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb6kjd.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb6kje.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb6kjf.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb6kjh.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb6kjj.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb6kjp.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb6kjq.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb6kjr.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb6kjt.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb6ksu.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb6ksv.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb6lc7.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb6lc8.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb6lc9.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb6lox.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb6m5h.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb6m5p.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb6m5q.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb6m7i.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb6md8.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb6mey.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb6mgh.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb6mia.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb6mk6.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb6mka.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb6mkf.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb6mkg.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb6mkh.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb6mki.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb6mkj.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb6mkq.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb6mll.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb6mnp.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb6mpq.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb6mu9.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb6muq.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb6mz1.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb6mz2.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb6n14.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb6n1n.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb6n6w.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb6n6x.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb6n6y.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb6n9k.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb6nfd.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb6nhs.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb6ni1.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb6niq.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb6nj1.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb6njk.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb6nlw.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb6ntz.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb6nvt.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb6nvu.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb6nz8.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb6o9s.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb6o9w.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb6oap.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb6ooe.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb6oof.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb6ooh.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb6ooj.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb6ook.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb6osu.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb6p52.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb6p53.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb6p54.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb6p55.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb6p56.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb6p96.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb6p97.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb6p98.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb6p99.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb6p9c.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb6pk0.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb6pl5.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb6pl6.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb6pq8.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb6pq9.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb6pqc.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb6pqi.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb6psg.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb6psk.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb6pt1.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb6pt5.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb6ptu.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb6pwl.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb6pwm.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb6px4.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb6pxe.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb6pxx.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb6q35.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb6q5b.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb6q5f.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb6q9n.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb6qw7.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb6qw8.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb6qw9.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb6qwa.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb6qwb.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb6qwc.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb6qwd.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb6qwe.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb6r3x.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb6r40.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb6r42.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb6rj7.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb6rtn.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb6s1s.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb6skp.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb6skq.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb6skr.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb6sp6.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb6syn.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb6t1h.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb6t35.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb6t3d.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb6t5y.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb6t7l.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb6tbw.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb6td0.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb6td1.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb6tpm.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb6ts9.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb6tww.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb6txd.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb6ty6.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb6tzf.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb6tzg.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb6tzh.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb6tzi.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb6tzj.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb6u58.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb6ue2.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb6ujg.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb6ujm.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb6uk6.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb6ukb.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb6ul9.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb6ula.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb6ulg.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb6ulj.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb6umc.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb6umd.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb6ume.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb6umf.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb6un1.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb6un3.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb6unb.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb6uqs.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb6uqt.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb6uqu.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb6ur3.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb6uvk.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb6v1j.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb6v1o.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb6v4w.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb6v5e.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb6v6g.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb6v6p.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb6v7h.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb6v7i.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb6v7t.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb6v83.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb6v8v.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb6vbc.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb6vbd.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb6vbl.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb6vbm.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb6vhs.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb6vje.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb6vnu.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb6vot.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb6w2z.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb6w33.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb6w34.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb6w5e.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb6w5f.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb6w5g.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb6w5o.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb6wa7.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb6wgp.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb6wgq.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb6wgr.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb6whf.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb6wif.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb6wip.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb6wjm.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb6wy4.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb6x9y.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb6xd5.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb6xd7.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb6xfs.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb6xg1.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb6xj3.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb6xj8.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb6xqr.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb6xqv.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb6xqx.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb6xqy.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb6xqz.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb6y6u.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb6y6z.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb6yen.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb6yeo.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb6yn0.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb6ypd.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb6yra.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb6yrs.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb6z21.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb6z22.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb6z23.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb6z24.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb6z25.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb6z7h.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb6z7i.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb6z7j.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb6z7k.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb6zrg.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb6zrh.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb6zri.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb6zrj.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb6zrp.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb6zw2.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb6zxi.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb7a5t.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb7a5u.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb7a5w.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb7a61.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb7a6z.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb7a71.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb7a72.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb7a74.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb7ass.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb7ato.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb7atw.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb7atx.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb7au0.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb7au1.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb7au8.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb7au9.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb7aub.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb7auh.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb7aux.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb7aw5.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb7b3r.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb7b3s.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb7b3u.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb7bdr.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb7bds.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb7bh3.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb7bh4.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb7bh5.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb7bh6.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb7bh7.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb7bn9.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb7cin.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb7ct3.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb7cy1.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb7d5j.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb7ddm.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb7dml.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb7doo.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb7e9a.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb7jhq.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb7jwl.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb7k2w.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb7k2x.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb7k2y.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb7k3m.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb7k5v.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb7k8e.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb7k8f.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb7k8h.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb7k8k.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb7k8l.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb7kcv.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb7kcw.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb7kcx.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb7kcy.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb7kep.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb7keq.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb7ker.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb7kh9.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb7khq.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb7khy.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb7khz.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb7kis.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb7kit.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb7kiv.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb7kiw.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb7l5r.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb7l5t.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb7l5v.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb7l8o.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb7lc4.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb7ljk.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb7lk8.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb7llb.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb7llh.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb7lnl.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb7lno.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb7lnq.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb7lnr.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb7lq6.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb7lxg.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb7ly1.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb7me9.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb7mea.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb7meb.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb7mec.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb7med.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb7mee.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb7mef.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb7meg.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb7meh.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb7mqn.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb7o49.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb7o4b.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb7oda.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb7ok9.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb7onk.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb7onn.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb7ono.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb7onw.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb7onx.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb7ony.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb7onz.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb7q0y.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb7q0z.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb7q11.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb7q3d.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb7qq5.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb7qqc.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb7r3q.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb7r3r.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb7r6z.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb7rcw.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb7rcx.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb7rcy.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb7rcz.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb7rd0.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb7ren.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb7rgg.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb7rl8.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb7rlr.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb7s0v.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb7sbm.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb7sbn.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb7t7d.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb7t7e.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb7t7f.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb7t7g.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb7tb7.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb7tbx.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb7tc1.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb7ti0.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb7u48.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb7u49.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb7u4b.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb7u4h.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb7u57.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb7v1y.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb7v1z.ent.gz pdb
cp ~/pdb/pdb/zipped/pdb7v21.ent.gz pdb
